"""经过口径审计的中东公开命名油气资产目录（DEMO）。

设计原则：一个记录对应一个可公开识别的油田、气田、区块或项目；
未公开的逐田数值保留为空，不以国家/油田群数据填充。
有坐标记录为公开地图资料的近似中心点；无核验坐标的记录只列目录。
"""

from __future__ import annotations

from typing import Any


SOURCES = {
    "ADNOC Onshore": "https://www.adnoc.ae/en/adnoc-onshore/about-us/what-we-do",
    "ADNOC Offshore": "https://www.adnoc.ae/en/adnoc-offshore",
    "ADNOC Al Yasat": "https://adnoc.ae/en/al-yasat-petroleum/about-us/what-we-do",
    "ADNOC Ghasha": "https://adnoc.ae/en/news-and-media/press-releases/2025/uae-president-chairs-adnoc-board-of-directors-meeting-at-habshan-complex",
    "Dubai Petroleum": "https://www.dubaipetroleum.ae/about-us/oil-and-gas-assets/",
    "Saudi Aramco / EIA": "https://www.eia.gov/international/analysis/country/SAU",
    "EIA Iran": "https://www.eia.gov/international/content/analysis/countries_long/Iran/pdf/Iran%20CAB%202024.pdf",
    "EIA Iraq": "https://www.eia.gov/international/analysis/country/irq",
    "KOC / KPC": "https://www.kockw.com/sites/EN/Pages/Profile/whoAreWe/KOC-History.aspx",
    "QatarEnergy": "https://www.qatarenergy.qa/en/MediaCenter/Publications/QatarEnergy_Investors_Presentation_November_2025.pdf",
    "PDO": "https://www.pdo.co.om/en/Pages/WhoWeAre/OurJourney.aspx",
    "Bapco": "https://www.bapco.net/en/page/history/",
    "Yemen Ministry of Oil": "https://mom-ye.com/site-en/",
    "Syria public reporting": "https://www.reuters.com/business/energy/shell-seeks-exit-syrias-al-omar-oilfield-official-says-2026-01-19/",
    "Le Monde Al-Omar 2026": "https://www.lemonde.fr/en/economy/article/2026/02/22/the-syrian-oil-sector-s-year-zero_6750756_19.html",
    "Israel Ministry of Energy": "https://prime.energy.gov.il/en/prime.html",
    "UNFCCC Bahrain BTR": "https://unfccc.int/sites/default/files/resource/30112025_Bahrain%27s_BTR1_2024_to_the_UNFCCC_vSubmitted.pdf",
    "KOC Annual Report 2023-24": "https://www.kockw.com/sites/EN/Annual%20Reports/2023%20-%202024%20English.pdf",
    "Masirah Oil Yumna": "https://www.masirahoil.om/post/production-update-march-2026",
    "GEM Yibal": "https://www.gem.wiki/Yibal_Oil_and_Gas_Field_(Oman)",
    "OQ / GEM Bisat": "https://oq.com/en/news-and-media/newsroom/20230126-oq-celebrates-inauguration-of-bisat-oil-field",
    "Shafaq News Faihaa": "https://shafaq.com/en/Economy/Iraq-expands-oil-production-starts-drilling-in-border-region",
    "Iraqi News West Qurna-1": "https://www.iraqinews.com/iraq/iraq-to-raise-west-qurna-1s-output-to-670000-bpd-in-2026/",
    "GEM Fakkah": "https://www.gem.wiki/Fakkah_Oil_Field_(Iraq)",
    "GEM Bazerkan": "https://www.gem.wiki/Bazerkan_Oil_Field_(Iraq)",
    "GEM Abu Gharb": "https://www.gem.wiki/Abu_Gharb_Oil_Field_(Iraq)",
    "GEM Luhais": "https://www.gem.wiki/Luhais_Oil_Field_(Iraq)",
    "GEM Subba": "https://www.gem.wiki/Subba_Oil_Field_(Iraq)",
    "GEM Tuba": "https://www.gem.wiki/Tuba_Oil_and_Gas_Field_(Iraq)",
    "GEM Bibi Hakimeh": "https://www.gem.wiki/Bibi_Hakimeh_Oil_Field_(Iran)",
    "GEM Karanj": "https://www.gem.wiki/Karanj_Oil_Field_(Iran)",
    "GEM Abuzar": "https://www.gem.wiki/Abuzar_Oil_Field_(Iran)",
    "GEM Mansouri": "https://www.gem.wiki/Mansouri_Oil_Field_(Iran)",
    "GEM Sepehr-Jufair": "https://www.gem.wiki/Sepehr-Jufair_Oil_Field_(Iran)",
    "GEM Parsi": "https://www.gem.wiki/Parsi_Oil_Field_(Iran)",
    "GEM Bahregansar": "https://www.gem.wiki/Bahregansar_Oil_Field_(Iran)",
    "GEM Sirri E": "https://www.gem.wiki/Sirri_E_Oil_and_Gas_Field_(Iran)",
    "GEM Masjed Soleyman": "https://www.gem.wiki/Masjed_Soleyman_Oil_Field_(Iran)",
    "GEM Marun": "https://www.gem.wiki/Marun_Oil_Field_(Iran)",
    "GEM Aghajari": "https://www.gem.wiki/Aghajari_Oil_Field_(Iran)",
    "GEM Gachsaran": "https://www.gem.wiki/Gachsaran_Oil_and_Gas_Field_(Iran)",
    "GEM South Azadegan": "https://www.gem.wiki/Azadegan_South_Oil_Field_(Iran)",
    "Trend North Azadegan": "https://www.trend.az/iran/business/3153217.html",
    "TPAO": "https://www.tpao.gov.tr/",
    "Rumaila Operating Organisation": "https://rumaila.iq/english/about-us/history-2/",
    "DNO 2025 Results": "https://www.dno.no/media/t14pl1zl/2025-interim-results-report.pdf",
    "Gulf Keystone H1 2026": "https://www.gulfkeystone.com/2026-half-year-results-announcement/",
    "ShaMaran Q2 2026": "https://shamaranpetroleum.com/news/shamaran-reports-second-quarter-2026-results-122891/",
    "PETRONAS Gharraf": "https://www.petronas.com/partner-us/pcihbv-contract-plan",
    "KOC Annual Report 2024-25": "https://www.kockw.com/sites/EN/Annual%20Reports/2024-2025%20English.pdf",
    "Saudi Press Agency 2025": "https://www.spa.gov.sa/en/N2295070",
    "Saudi Press Agency 2024": "https://www.spa.gov.sa/N2131725",
    "Daleel Petroleum": "https://daleelpetroleum.com/operational-excellence/production",
    "Occidental Oman": "https://www.oxy.com/operations/performance-production/",
    "GEM Pazanan": "https://www.gem.wiki/Pazanan_Oil_Field_(Iran)",
    "GEM Kupal": "https://www.gem.wiki/Kupal_Oil_Field_(Iran)",
    "GEM Dehloran": "https://www.gem.wiki/Dehloran_Oil_Field_(Iran)",
    "GEM Paranj": "https://www.gem.wiki/Paranj_Oil_Field_(Iran)",
    "GEM Nargesi": "https://www.gem.wiki/Nargesi_Oil_Field_(Iran)",
    "Aramco 2019 Prospectus": "https://www.aramco.com/-/media/images/investors/saudi-aramco-prospectus-en-051219.pdf",
    "Iraq EITI 2021": "https://eiti.org/sites/default/files/2024-01/Iraq%202021%20EITI%20Report.pdf",
    "Iraq EITI 2016": "https://eiti.org/sites/default/files/attachments/iraq_2016_eiti_report.pdf",
    "QatarEnergy E&P": "https://www.qatarenergy.qa/en/Whatwedo/Pages/ExplorationandProduction.aspx",
    "ADOC Fields": "https://www.cts-co.net/adocauh/product/",
    "Aramco FY2025 Results": "https://china.aramco.com/zh-cn/news-media/global-news/2026/aramco-announces-fourth-quarter-and-full-year-2025-results",
    "Aramco 2019 Increments": "https://www.aramco.com/en/news-media/news/2019/aramco-contracts-marjan-berri-oilfields",
    "Aramco 2019 GMTN": "https://www.aramco.com/-/media/publications/corporate-reports/bonds/2019-gmtn-prospectus.pdf",
    "Iraq EITI 2019-20": "https://eiti.org/sites/default/files/2023-01/doc-1232-2022_12_15_11_48_01.pdf",
    "SHANA Hengam 2010": "https://www.shana.ir/news/156860/",
    "KOC Mutriba": "https://www.kockw.com/sites/EN/EMagazine/Pages/Events/1032.aspx",
    "OQEP Operations": "https://www.oqep.om/operation",
    "SNOC Upstream": "https://www.snoc.ae/our-business/upstream/",
    "SNOC GHG 2021": "https://www.snoc.ae/wp-content/uploads/SNOC-2021-GHG-Report.pdf",
    "RAKGAS History": "https://www.rakgas.ae/en/who-we-are/our-story",
    "Bapco Abu Safah": "https://www.bapco.net/en/page/crude-and-petroleum-products",
    "Aramco 2017 Review": "https://www.aramco.com/en/news-media/news/2018/2017-annual-review",
    "Aramco 2025 Highlights": "https://www.aramco.com/en/investors/annual-report/highlights",
    "Aramco Gas 2026": "https://www.aramco.com/en/news-media/news/2026/aramcos-gas-strategy-builds-momentum-with-major-progress-towards-growth-target",
    "ADNOC Bab 2019": "https://adnoc.ae/en/news-and-media/press-releases/2019/adnoc-invests-aed-1-8-billion-to-upgrade-its-giant-bab-onshore-field",
    "ADNOC Bu Hasa 2021": "https://www.adnoc.ae/news-and-media/press-releases/2021/adnoc-invests-usd318-million-to-connect-smart-wells-at-bu-hasa",
    "ADNOC Shah 2025": "https://adnoc.ae/en/news-and-media/press-releases/2025/adnoc-achieves-industryleading-carbon-intensity-at-shah",
    "ADNOC Lower Zakum 2022": "https://adnoc.ae/en/news-and-media/press-releases/2022/adnoc-announces-%24548-million-contract-for-a-new-main-gas-line-at-its-lower-zakum-field",
    "INPEX Upper Zakum 2017": "https://www.inpex.com/english/news/english/news/assets/pdf/e20171114.pdf",
    "ADNOC Umm Shaif 2022": "https://www.adnoc.ae/en/news-and-media/press-releases/2022/adnoc-invests-close-to-usd1-billion-in-the-long-term-development-of-umm-shaif-field",
    "INPEX Nasr 2015": "https://www.inpex.com/english/news/english/news/assets/pdf/e20150205.pdf",
    "INPEX Umm Lulu 2014": "https://www.inpex.com/english/news/english/news/assets/pdf/e20141017.pdf",
    "ADNOC SARB 2024": "https://adnoc.ae/en/news-and-media/press-releases/2023/adnocs-offshore-sarb-field-commences-ai-enabled-digital-operations",
    "ADNOC Belbazem 2024": "https://adnoc.ae/en/news-and-media/press-releases/2023/adnoc-announces-first-production-from-belbazem-offshore-block/",
    "ADNOC Haliba": "https://www.adnoc.ae/en/al-dhafra-petroleum/about-us/what-we-do",
    "Iraq EITI 2023": "https://eiti.org/documents/iraq-2023-eiti-report",
    "HKN Sarsang": "https://www.hknenergy.com/",
    "Kurdistan Presidency 2025": "https://presidency.gov.krd/en/statement-from-the-presidency-of-the-kurdistan-region-5/",
    "Genel Q1 2024": "https://genelenergy.com/wp-content/uploads/Genel-2024-Q1-trading-update.pdf",
    "DNO Kurdistan 2025": "https://www.dno.no/en/operations/kurdistan-region-of-iraq/",
    "Daleel 2023": "https://daleelpetroleum.com/media/news/2023/daleel-petroleum-a-journey-of-excellence",
    "PDO Sustainability 2024": "https://www.pdo.co.om/en/PDOSERVICES/Sustainability%20Report%202024%20English.pdf",
    "GEM Darquain": "https://www.gem.wiki/Darquain_Oil_Field_%28Iran%29",
    "Qatar News Agency A-Structures": "https://qna.org.qa/en/news/news-details?date=23%2F12%2F2022&id=0056-qatarenergy-signs-agreement-with-qpd-to-continue-al-karkara%2C-a-structures-offshore-fields-development-and-production",
    "Yemen EIA": "https://www.eia.gov/international/content/analysis/countries_long/Yemen/yemen.pdf",
    "Yemen PEPA Production Plan": "https://pepaye.com/production/plan",
    "Rudaw Rmeilan Sector One": "https://www.rudaw.net/english/categories/syria/933427",
    "Egypt EGPC Brownfields 2023": "https://eug.petroleum.gov.eg/dp/jsp/assets/docs/EGPC/2023%20EGPC%20Brownfields%20Overview.pdf",
    "Eni Egypt Factbook 2013": "https://report.eni.com/factbook-2013/en/business-segments/exploration-production/activity-areas/north-africa.html",
}


def record(
    country: str,
    name: str,
    name_cn: str,
    asset_type: str,
    lat: float | None,
    lon: float | None,
    *,
    value: str | None = None,
    metric_type: str = "undisclosed",
    unit: str | None = None,
    data_date: str | None = None,
    status: str = "公开命名资产",
    source: str,
    note: str = "",
) -> dict[str, Any]:
    return {
        "country": country,
        "name": name,
        "name_cn": name_cn,
        "asset_type": asset_type,
        "lat": lat,
        "lon": lon,
        "value": value,
        "metric_type": metric_type,
        "unit": unit,
        "data_date": data_date,
        "status": status,
        "coordinate_precision": "近似中心点" if lat is not None and lon is not None else "待核验；仅列目录",
        "source": source,
        "source_url": SOURCES[source],
        "note": note,
    }


# 仅在来源给出明确的单一资产口径时填写 value；区块／项目数值不可归给组成油田。
ASSETS = [
    # Saudi Arabia
    record("沙特阿拉伯", "Ghawar", "加瓦尔", "油田", 25.42, 49.57, value="3,800", metric_type="maximum_sustainable_capacity", unit="千桶/日", data_date="2018-12-31", source="Aramco 2019 Prospectus", note="阿美招股书表14最大可持续产能，不是当期实际产量。"),
    record("沙特阿拉伯", "Safaniya", "萨法尼亚", "海上油田", 28.18, 48.78, value="1,300", metric_type="maximum_sustainable_capacity", unit="千桶/日", data_date="2018-12-31", source="Aramco 2019 Prospectus", note="阿美招股书截至2018年末最大可持续产能；非实际日产量。"),
    record("沙特阿拉伯", "Khurais", "库赖斯", "油田／综合体", 25.03, 48.24, value="1,450", metric_type="maximum_sustainable_capacity", unit="千桶/日", data_date="2018-12-31", source="Aramco 2019 Prospectus", note="阿美公布的Khurais综合体最大可持续产能，含Abu Jifan、Mazalij等，不能分配给Khurais单田；非实际产量。"),
    record("沙特阿拉伯", "Shaybah", "谢拜", "油田", 22.48, 53.78, value="1,000", metric_type="maximum_sustainable_capacity", unit="千桶/日", data_date="2018-12-31", source="Aramco 2019 Prospectus", note="阿美招股书表14最大可持续产能，非当前实际日产量。"),
    record("沙特阿拉伯", "Manifa", "马尼法", "海上油田", 27.62, 49.87, value="900", metric_type="capacity", unit="千桶/日", data_date="2019年招股书披露", source="Aramco 2019 Prospectus", note="阿美招股书列马尼法原油生产能力90万桶/日；披露时点的历史产能，非当前实产。"),
    record("沙特阿拉伯", "Marjan", "马尔詹", "海上油田", 27.47, 49.86, value="300", metric_type="incremental_capacity", unit="千桶/日", data_date="2025年项目投产", source="Aramco FY2025 Results", note="2025年投产项目的新增产能，并非油田总产能或实际日产量。"),
    record("沙特阿拉伯", "Berri", "贝里", "海上油田", 27.83, 49.93, value="250", metric_type="planned_incremental_capacity", unit="千桶/日", data_date="2019-07-09规划；截至2025年末注水启动", source="Aramco 2019 Increments", note="项目规划新增原油产能；阿美2025全年业绩仅称注水作业已启动，未证实该增量已投产，不能作实际日产量。"),
    record("沙特阿拉伯", "Zuluf", "祖卢夫", "海上油田", 27.67, 49.12, value="825", metric_type="maximum_sustainable_capacity", unit="千桶/日", data_date="2018-12-31", source="Aramco 2019 Prospectus", note="阿美招股书截至2018年末最大可持续产能；不能与后续项目新增/处理能力混同，非实际日产量。"),
    record("沙特阿拉伯", "Qatif", "卡提夫", "油田", 26.55, 50.01, source="Saudi Aramco / EIA"),
    record("沙特阿拉伯", "Abqaiq", "阿布盖格", "油田", 25.94, 49.68, source="Saudi Aramco / EIA"),
    record("沙特阿拉伯", "Khursaniyah", "胡尔萨尼亚", "油田", 27.72, 48.91, source="Saudi Aramco / EIA"),
    record("沙特阿拉伯", "Dammam", "达曼", "油田", 26.36, 49.99, value="25", metric_type="incremental_capacity", unit="千桶/日", data_date="2025年第二季度投产", source="Aramco 2025 Highlights", note="达曼开发一期新增原油产能，不是整个油田实际日产量。"),
    record("沙特阿拉伯", "Jafurah", "贾富拉", "非常规气田", 25.43, 48.82, status="2026年宣布开始产气", source="Aramco Gas 2026", note="阿美2026年确认气田开始生产；天然气或油当量数据不作为原油逐田日产量。"),
    # 2025 年公布的新发现：井测试流量不是油田持续日产量；未核验点位不绘地图标。
    record("沙特阿拉伯", "Jabu", "贾布", "发现油田", None, None, status="已发现；商业生产未证实", source="Saudi Press Agency 2025", note="官方公布的新发现油田；试井流量不填作油田日产量。"),
    record("沙特阿拉伯", "Sayahid", "萨亚希德", "发现油田", None, None, status="已发现；商业生产未证实", source="Saudi Press Agency 2025", note="官方公布的新发现油田；逐田实产未披露。"),
    record("沙特阿拉伯", "Ayfan", "艾凡", "发现油田", None, None, status="已发现；商业生产未证实", source="Saudi Press Agency 2025", note="官方公布的新发现油田；逐田实产未披露。"),
    record("沙特阿拉伯", "Nuwayr", "努韦尔", "发现油田", None, None, status="已发现；商业生产未证实", source="Saudi Press Agency 2025", note="官方公布的新发现油田；逐田实产未披露。"),
    record("沙特阿拉伯", "Damda", "达姆达", "发现油田", None, None, status="已发现；商业生产未证实", source="Saudi Press Agency 2025", note="官方公布的新发现油田；逐田实产未披露。"),
    record("沙特阿拉伯", "Qurqas", "古尔加斯", "发现油田", None, None, status="已发现；商业生产未证实", source="Saudi Press Agency 2025", note="官方公布的新发现油田；逐田实产未披露。"),
    record("沙特阿拉伯", "Ladam", "拉达姆", "非常规发现油田", None, None, status="2024年发现；商业生产未证实", source="Saudi Press Agency 2024", note="官方公布的非常规油田；5,100桶/日是Ladam-2井测试流量，不是全田持续日产量。"),
    record("沙特阿拉伯", "Faruq", "法鲁克", "非常规发现油田", None, None, status="2024年发现；商业生产未证实", source="Saudi Press Agency 2024", note="官方公布的非常规油田；4,557桶/日是Faruq-4井测试流量，不是全田持续日产量。"),

    # Aramco prospectus identifies these as separate fields within the Khurais complex; no field-level production split.
    record("沙特阿拉伯", "Abu Jifan", "阿布吉凡", "油田（Khurais综合体）", None, None, source="Aramco 2019 Prospectus", note="阿美列为Khurais综合体组成油田；综合体1,450千桶/日产能不可拆给单田。"),
    record("沙特阿拉伯", "Mazalij", "马扎利吉", "油田（Khurais综合体）", None, None, source="Aramco 2019 Prospectus", note="阿美列为Khurais综合体组成油田；单田产量未披露。"),
    record("沙特阿拉伯", "Qirdi", "吉尔迪", "油田（Khurais综合体）", None, None, source="Aramco 2019 Prospectus", note="阿美储量认证附件列为单独油田；部分综合体描述未列此田，单田产量未披露。"),
    record("沙特阿拉伯", "Abu Hadriya", "阿布哈德里亚", "油田", None, None, source="Aramco 2019 Prospectus", note="阿美储量认证附件列为油田；生产状态及逐田日产量待核。"),
    record("沙特阿拉伯", "Fadhili", "法迪利", "油田", None, None, source="Aramco 2019 Prospectus", note="阿美储量认证附件列为油田；与同名气体处理设施区分，逐田原油日产量待核。"),
    record("沙特阿拉伯", "Harmaliyah", "哈马利亚", "油田", None, None, source="Aramco 2019 Prospectus", note="阿美储量认证附件列为油田；逐田产量未披露。"),
    record("沙特阿拉伯", "Hawtah", "豪塔", "油田", None, None, source="Aramco 2019 GMTN", note="阿美2019年债券招股书第100页原油基础设施图列名；逐田产量及坐标未核验。"),
    record("沙特阿拉伯", "Sakab", "萨卡布", "发现油田", None, None, status="2017年发现；商业生产未核", source="Aramco 2017 Review", note="阿美2017年度回顾列为新发现油田；无可核验单田持续日产量。"),
    record("沙特阿拉伯", "Zumul", "祖穆尔", "发现油田", None, None, status="2017年发现；商业生产未核", source="Aramco 2017 Review", note="阿美2017年度回顾列为鲁卜哈利新发现油田；无可核验单田持续日产量。"),

    # United Arab Emirates — ADNOC Onshore
    record("阿联酋", "Bab", "巴布", "油田", 23.93, 53.79, value="450", metric_type="target_capacity", unit="千桶/日", data_date="2019-11-13公告；此前合同目标2020年", source="ADNOC Bab 2019", note="ADNOC回顾此前将产能从420提高至450千桶/日的2020年目标，另提出485千桶/日长期维持项目；均非已核实实产。"),
    record("阿联酋", "Bu Hasa", "布哈萨", "油田", 23.52, 53.24, value="650", metric_type="capacity", unit="千桶/日", data_date="2021-05-10公告", source="ADNOC Bu Hasa 2021", note="ADNOC称投资维持该田650千桶/日产能；不是逐日实际产量。"),
    record("阿联酋", "Huwaila", "胡韦拉", "油田", 23.70, 53.45, source="ADNOC Onshore"),
    record("阿联酋", "Bida Al-Qemzan", "比达·盖姆赞", "油田", 23.66, 53.66, source="ADNOC Onshore"),
    record("阿联酋", "Al Dabb'iya", "达比亚", "油田", 24.36, 54.15, source="ADNOC Onshore"),
    record("阿联酋", "Rumaitha", "鲁迈萨", "油田", 24.30, 54.22, source="ADNOC Onshore"),
    record("阿联酋", "Shanayel", "沙奈耶勒", "油田", 24.18, 54.27, source="ADNOC Onshore"),
    record("阿联酋", "Asab", "阿萨布", "油田", 23.45, 53.77, source="ADNOC Onshore"),
    record("阿联酋", "Sahil", "萨希勒", "油田", 23.55, 53.90, source="ADNOC Onshore"),
    record("阿联酋", "Shah", "沙阿", "油气田", 22.99, 53.95, value="70", metric_type="oil_capacity", unit="千桶/日", data_date="2025-01-23公告", source="ADNOC Shah 2025", note="原油产能约70千桶/日；与同名气体处理能力分开，非实产。"),
    record("阿联酋", "Qusahwira", "古萨赫维拉", "油田", 23.23, 54.18, source="ADNOC Onshore"),
    record("阿联酋", "Mender", "门德尔", "油田", 23.08, 54.00, source="ADNOC Onshore"),
    record("阿联酋", "Jumaylah", "朱迈拉", "油田", 24.05, 53.70, status="公开命名；生产状态待确认", source="ADNOC Onshore"),
    record("阿联酋", "Al Nouf", "努夫", "油田", 24.11, 53.82, status="公开命名；生产状态待确认", source="ADNOC Onshore"),

    # United Arab Emirates — ADNOC Offshore
    record("阿联酋", "Upper Zakum", "上扎库姆", "海上油田", 24.85, 53.66, value="1,000", metric_type="target_capacity", unit="千桶/日", data_date="2017-11-14协议；目标2024年", source="INPEX Upper Zakum 2017", note="合作伙伴2017年提出的产能提升目标；未据此认定2024年已达产，更不是实际日产量。"),
    record("阿联酋", "Lower Zakum", "下扎库姆", "海上油田", 24.74, 53.51, value="450", metric_type="target_capacity", unit="千桶/日", data_date="2022-09-05公告；目标2025年", source="ADNOC Lower Zakum 2022", note="ADNOC称产能计划在2025年提高到450千桶/日；未找到已实现的逐田产能或实产确认。"),
    record("阿联酋", "Umm Shaif", "乌姆沙伊夫", "海上油田", 25.26, 53.28, value="275", metric_type="capacity", unit="千桶/日", data_date="2022-01-05公告", source="ADNOC Umm Shaif 2022", note="ADNOC公布维持现有275千桶/日产能的项目；非实际日产量。"),
    record("阿联酋", "Satah", "萨塔赫", "海上油田", 25.10, 52.74, source="ADNOC Offshore"),
    record("阿联酋", "Nasr", "纳斯尔", "海上油田", 25.54, 53.52, value="65", metric_type="target_capacity", unit="千桶/日", data_date="2015-02-05公告；全田开发预期峰值", source="INPEX Nasr 2015", note="INPEX在初期投产公告中预期全田开发完成后峰值65千桶/日；未核实实际达到或当前实产。"),
    record("阿联酋", "Umm Al Dalkh", "乌姆阿尔达尔赫", "海上油田", 24.63, 54.10, source="ADNOC Offshore"),
    record("阿联酋", "Satah Al Razboot (SARB)", "萨塔赫·阿尔拉兹布特", "海上油气田", 25.19, 53.18, value="140", metric_type="capacity", unit="千桶/日", data_date="2024-07-30公告", source="ADNOC SARB 2024", note="ADNOC宣布该田达到140千桶/日产能；非实际日产量，深层气项目单列。"),
    record("阿联酋", "Umm Lulu", "乌姆卢卢", "海上油田", 24.70, 54.06, value="105", metric_type="target_capacity", unit="千桶/日", data_date="2014-10-17公告；全田开发预期峰值", source="INPEX Umm Lulu 2014", note="INPEX初期投产公告称全田开发完成后预期峰值105千桶/日；不能认定已经达到。"),
    record("阿联酋", "Abu Al Bukhoosh", "阿布阿尔布胡什", "海上油田", 25.50, 53.15, source="ADNOC Offshore"),

    # United Arab Emirates — Al Yasat / Ghasha / other concessions
    record("阿联酋", "Bu Haseer", "布哈塞尔", "海上油田", 24.93, 53.17, value="8", metric_type="actual_output", unit="千桶/日", data_date="2018年3月初期投产口径", source="ADNOC Al Yasat", note="ADNOC称初期生产方案日产8千桶；全田15千桶/日仅是目标，未用目标代替实产；本值并非当前产量。"),
    record("阿联酋", "Belbazem", "贝尔巴泽姆", "海上油田", 25.13, 53.59, source="ADNOC Belbazem 2024", note="2024年投产的Belbazem区块组成油田之一；45千桶/日属于三区块合计目标，单田实产未披露。"),
    record("阿联酋", "Belbazem Offshore Block", "贝尔巴泽姆海上区块", "海上区块（三油田）", None, None, value="45", metric_type="target_capacity", unit="千桶/日", data_date="2024-03-27公告；逐步达产目标", source="ADNOC Belbazem 2024", note="目标为Belbazem、Umm Al Salsal、Umm Al Dholou三田合计产能，非任一单田或已核实实产；区块无单点坐标。"),
    record("阿联酋", "Umm Al Salsal", "乌姆阿尔萨尔萨勒", "海上油田", 25.07, 53.53, source="ADNOC Al Yasat"),
    record("阿联酋", "Umm Al Dholou", "乌姆阿尔祖卢", "海上油田", 25.01, 53.64, source="ADNOC Al Yasat"),
    record("阿联酋", "Arzanah", "阿尔扎纳", "海上油田", 24.79, 52.56, source="ADNOC Al Yasat"),
    record("阿联酋", "Nahaidiin", "纳海迪因", "油田", 23.82, 52.20, source="ADNOC Al Yasat"),
    record("阿联酋", "Bin Hadi", "本哈迪", "油田", 23.72, 52.43, source="ADNOC Al Yasat"),
    record("阿联酋", "Gezira", "盖济拉", "油田", 23.89, 52.61, source="ADNOC Al Yasat"),
    record("阿联酋", "Muhaymat", "穆海马特", "浅海油田", 24.10, 52.10, source="ADNOC Al Yasat"),
    record("阿联酋", "Sila", "锡拉", "浅海油田", 24.08, 51.76, source="ADNOC Al Yasat"),
    record("阿联酋", "Ghasha", "加沙", "超酸性气田", 24.95, 52.77, source="ADNOC Ghasha"),
    record("阿联酋", "Dalma", "达尔马", "超酸性气田", 24.78, 52.83, source="ADNOC Ghasha"),
    record("阿联酋", "Shuweihat", "舒韦哈特", "超酸性气田", 24.20, 52.55, source="ADNOC Ghasha"),
    record("阿联酋", "SARB Deep Gas", "SARB 深层气项目", "天然气项目", 25.19, 53.18, value="200", metric_type="target_capacity", unit="百万标准立方英尺/日", data_date="2026-01-07", source="ADNOC Ghasha", note="天然气项目，不能与原油日产量相加。"),
    record("阿联酋", "Hail (ADOC)", "海尔（ADOC）", "海上油田", 24.37, 53.41, status="2017年投产", source="ADOC Fields", note="ADOC确认Hail与Mubarraz等田的原油混合外运；原列21千桶/日未在该单田来源中核实，撤回。"),
    record("阿联酋", "Hail (ADNOC Ghasha)", "海尔（ADNOC Ghasha）", "含酸气海上油气田", None, None, status="ADNOC列为Ghasha开发项目组成资产；单田投产状态待核", source="ADNOC Ghasha", note="与上方Hail (ADOC)是不同资产。ADNOC将Hail列入Ghasha项目；项目层级的气量／液体目标不分摊为该田产量，单田坐标和产量未核实。"),
    record("阿联酋", "Mubarraz", "穆巴拉兹", "海上油田", 24.40, 53.52, source="ADNOC Ghasha"),
    record("阿联酋", "Umm Al-Anbar", "乌姆阿尔安巴尔", "海上油田", 24.30, 53.45, source="ADNOC Ghasha"),
    record("阿联酋", "Neewat Al-Ghalan", "尼瓦特阿尔加兰", "海上油田", 24.22, 53.55, source="ADNOC Ghasha"),
    record("阿联酋", "Bunduq", "本杜克", "跨境海上油田", 25.22, 52.72, value="9.2", metric_type="actual_output", unit="千桶/日", data_date="2024年平均", source="QatarEnergy", note="QatarEnergy投资者材料第13页列El Bunduq全田2024年平均原油产量；跨境资产仅列一次，不是阿联酋权益量。"),
    record("阿联酋", "Haliba", "哈利巴", "油田", 23.00, 53.80, value="10", metric_type="actual_output", unit="千桶/日", data_date="2019年6月初期投产口径", source="ADNOC Haliba", note="ADNOC Al Dhafra称2019年6月开始以10千桶/日生产；40千桶/日仅为目标产能，本值非当前实产。"),
    record("阿联酋", "Fateh", "法泰赫", "海上油田", 25.54, 54.29, source="Dubai Petroleum"),
    record("阿联酋", "South-West Fateh", "西南法泰赫", "海上油田", 25.45, 54.19, source="Dubai Petroleum"),
    record("阿联酋", "Falah", "法拉赫", "海上油田", 25.63, 54.21, source="Dubai Petroleum"),
    record("阿联酋", "Rashid", "拉希德", "海上油田", 25.45, 54.40, source="Dubai Petroleum"),
    record("阿联酋", "Jalilah", "贾利拉", "海上油田", 25.38, 54.34, source="Dubai Petroleum"),
    record("阿联酋", "Margham", "马尔格姆", "凝析油气田", 24.98, 55.61, value="25", metric_type="historical_condensate_output", unit="千桶/日", data_date="2010-12-31", source="Dubai Petroleum", note="2010年凝析油，非当前原油日产量。"),
    record("阿联酋", "Bab Gas Cap", "巴布气顶项目", "天然气项目", 23.93, 53.79, value="1,500", metric_type="target_capacity", unit="百万标准立方英尺/日", data_date="2026-01-01", source="ADNOC Onshore", note="天然气项目。"),
    record("阿联酋", "Ruwais Diyab", "鲁韦斯迪亚布", "非常规气特许权", 24.15, 52.70, source="ADNOC Ghasha", note="特许权，不是单一油田。"),
    record("阿联酋", "Sajaa", "萨贾", "气／凝析油田", None, None, source="SNOC Upstream", note="沙迦SNOC列为既有油气资产；原油逐田日产量未披露。"),
    record("阿联酋", "Kahaif", "卡海夫", "气／凝析油田", None, None, source="SNOC Upstream", note="沙迦SNOC列为既有油气资产；原油逐田日产量未披露。"),
    record("阿联酋", "Moveyeid", "穆韦耶德", "气田／储气设施", None, None, status="成熟气田转为储气用途", source="SNOC Upstream", note="SNOC称其已从成熟生产田转型为储气设施；不填当期原油日产量。"),
    record("阿联酋", "Mahani", "马哈尼", "气／凝析油田", None, None, status="2020年发现；2021年运营中，当期待核", source="SNOC GHG 2021", note="SNOC的2021年温室气体报告列为其四座运营气田之一；不将井测试流量填为全田持续产量。"),
    record("阿联酋", "Hedebah", "赫德巴", "气／凝析油田", None, None, status="2024年发现；开发中", source="SNOC Upstream", note="SNOC将其列为新发现田；持续逐田产量未披露。"),
    record("阿联酋", "Saleh", "萨利赫", "海上气田", None, None, status="历史生产；当期状态待核", source="RAKGAS History", note="RAKGAS历史页面记载从哈伊马角近海Saleh田开采和处理，未披露当前逐田流量。"),
    record("阿联酋", "Umm Al Quwain", "乌姆盖万", "海上气田", None, None, status="历史生产；当期状态待核", source="RAKGAS History", note="RAKGAS历史页面记载2006—2008年处理该田来气；当前生产状态和逐田数值待核。"),

    # Iraq
    record("伊拉克", "Rumaila", "鲁迈拉", "油田", 30.08, 47.43, value="1,370", metric_type="actual_output", unit="千桶/日", data_date="2025年平均", source="Rumaila Operating Organisation", note="运营组织直报2025全年日均137万桶；不是当前瞬时日产量。"),
    record("伊拉克", "West Qurna-1", "西古尔纳一期", "油田", 30.77, 47.25, value="600", metric_type="actual_output", unit="千桶/日", data_date="2025-11-20", source="Iraqi News West Qurna-1", note="报道引用油田管理方称当日产量为600千桶/日；旧750千桶/日记录是产能，2026年实际日产量未核实。"),
    record("伊拉克", "West Qurna-2", "西古尔纳二期", "油田", 30.96, 47.31, value="400.1", metric_type="derived_daily_average", unit="千桶/日", data_date="2021年推算日均", source="Iraq EITI 2021", note="EITI 2021 表58（PCLD）年产146,022,515桶÷365日=400.1千桶/日（四舍五入）；历史均值，非当前日产量。"),
    record("伊拉克", "Zubair", "祖拜尔", "油田", 30.20, 47.82, value="470.6", metric_type="derived_daily_average", unit="千桶/日", data_date="2021年推算日均", source="Iraq EITI 2021", note="EITI 2021 表58（PCLD）年产171,760,022桶÷365日=470.6千桶/日（四舍五入）；历史均值，非当前日产量。"),
    record("伊拉克", "Majnoon", "马季努恩", "油田", 31.05, 47.72, value="176.0", metric_type="derived_daily_average", unit="千桶/日", data_date="2021年推算日均", source="Iraq EITI 2021", note="EITI 2021 表58（PCLD）年产64,240,000桶÷365日=176.0千桶/日（四舍五入）；历史均值，非当前日产量。"),
    record("伊拉克", "Halfaya", "哈法亚", "油田", 31.58, 47.30, value="389.6", metric_type="derived_daily_average", unit="千桶/日", data_date="2021年推算日均", source="Iraq EITI 2021", note="EITI 2021 表58（PCLD）年产142,213,694桶÷365日=389.6千桶/日（四舍五入）；历史均值，非当前日产量。"),
    record("伊拉克", "Gharraf", "加拉夫", "油田", 31.45, 46.78, value="130", metric_type="actual_output", unit="千桶/日", data_date="截至2022-04-20的运营资料", source="PETRONAS Gharraf", note="PETRONAS资料称该田平均约13万桶/日；网页给出2022-04-20累计出口基准日，属于历史资料。"),
    record("伊拉克", "Badra", "巴德拉", "油田", 33.03, 45.03, value="41.3", metric_type="derived_daily_average", unit="千桶/日", data_date="2021年推算日均", source="Iraq EITI 2021", note="EITI 2021 表58（PCLD）年产15,083,829桶÷365日=41.3千桶/日（四舍五入）；历史均值，非当前日产量。"),
    record("伊拉克", "Ahdab", "阿赫达卜", "油田", 32.99, 44.63, value="49.2", metric_type="derived_daily_average", unit="千桶/日", data_date="2021年推算日均", source="Iraq EITI 2021", note="EITI 2021 表58（PCLD）年产17,956,867桶÷365日=49.2千桶/日（四舍五入）；历史均值，非当前日产量。"),
    record("伊拉克", "East Baghdad", "东巴格达", "油田", 33.45, 44.60, value="27.1", metric_type="derived_daily_average", unit="千桶/日", data_date="2021年推算日均", source="Iraq EITI 2021", note="EITI 2021 表58（PCLD）年产9,900,000桶÷365日=27.1千桶/日（四舍五入）；历史均值，非当前日产量。"),
    record("伊拉克", "Nahr Umar", "纳赫尔乌马尔", "油田", 30.40, 47.72, value="3.0", metric_type="derived_daily_average", unit="千桶/日", data_date="2021年推算日均", source="Iraq EITI 2021", note="EITI 2021 表58（PCLD）年产1,109,514桶÷365日=3.0千桶/日（四舍五入）；历史均值，非当前日产量。"),
    record("伊拉克", "Artawi", "阿尔塔维", "油田", 30.42, 47.91, value="16.7", metric_type="derived_daily_average", unit="千桶/日", data_date="2016年推算日均", status="EITI 2023列为非生产田；后续待核", source="Iraq EITI 2016", note="EITI 2016报告第75页Basra Oil Company逐田年产6,123,726桶÷366日=16.7千桶/日（四舍五入）；EITI 2023表17列非生产田，不能据历史值认定当前产量。"),
    record("伊拉克", "Nassiriya", "纳西里耶", "油田", 31.12, 46.27, value="5.8", metric_type="derived_daily_average", unit="千桶/日", data_date="2021年推算日均", source="Iraq EITI 2021", note="EITI 2021 表58（PCLD）年产2,124,402桶÷365日=5.8千桶/日（四舍五入）；历史均值，非当前日产量。"),
    record("伊拉克", "Kirkuk", "基尔库克", "油田", 35.47, 44.39, source="EIA Iraq"),
    record("伊拉克", "Bai Hassan", "拜哈桑", "油田", 35.61, 44.40, value="133.3", metric_type="derived_daily_average", unit="千桶/日", data_date="2021年推算日均", source="Iraq EITI 2021", note="EITI 2021 表57（North Oil Company）；年产48,672,087桶÷365日=133.3千桶/日（四舍五入）；历史均值，非当前日产量。"),
    record("伊拉克", "Jambur", "詹布尔", "油田", 35.31, 44.48, value="38.4", metric_type="derived_daily_average", unit="千桶/日", data_date="2021年推算日均", source="Iraq EITI 2021", note="EITI 2021 表57（North Oil Company）；年产14,008,692桶÷365日=38.4千桶/日（四舍五入）；历史均值，非当前日产量。"),
    record("伊拉克", "Khabbaz", "哈巴兹", "油田", 35.52, 44.21, value="25.0", metric_type="derived_daily_average", unit="千桶/日", data_date="2021年推算日均", source="Iraq EITI 2021", note="EITI 2021 表57（North Oil Company）；年产9,139,429桶÷365日=25.0千桶/日（四舍五入）；历史均值，非当前日产量。"),
    record("伊拉克", "Qayyarah", "盖亚拉", "油田", 35.80, 43.31, source="EIA Iraq"),
    record("伊拉克", "Najma", "纳杰马", "油田", 35.91, 43.20, value="10.2", metric_type="derived_daily_average", unit="千桶/日", data_date="2021年推算日均", status="EITI 2023列为非生产田", source="Iraq EITI 2021", note="EITI 2021 表58（PCLD）年产3,720,000桶÷365日=10.2千桶/日（四舍五入）；EITI 2023报告表13列为非生产田，历史值不能视作当期日产量。"),
    record("伊拉克", "Tawke", "陶凯", "油田（库区）", 37.02, 43.27, value="29.095", metric_type="actual_output", unit="千桶/日", data_date="2025年第四季度平均", source="DNO 2025 Results", note="DNO直报全田总产量；不是DNO的75%权益产量。"),
    record("伊拉克", "Peshkabir", "佩什卡比尔", "油田（库区）", 37.13, 43.47, value="48.173", metric_type="actual_output", unit="千桶/日", data_date="2025年第四季度平均", source="DNO 2025 Results", note="DNO直报全田总产量；不是DNO的75%权益产量。"),
    record("伊拉克", "Taq Taq", "塔克塔克", "油田（库区）", 35.91, 44.62, value="1.36", metric_type="actual_output", unit="千桶/日", data_date="2023年平均", status="Genel称2023-05-20起停产；后续待核", source="Genel Q1 2024", note="运营方直报2023年全田总产量1,360桶/日（含停产期的年度平均）；不是Genel权益产量，更非当前日产量。"),
    record("伊拉克", "Sarta", "萨尔塔", "油田（库区）", None, None, value="0.79", metric_type="actual_output", unit="千桶/日", data_date="2023年平均", status="Sarta PSC于2023-12-01终止", source="Genel Q1 2024", note="Genel直报2023年全资产总产量790桶/日；合同随后终止，不能当作现时生产。未核验单田点位。"),
    record("伊拉克", "Shaikan", "沙伊坎", "油田（库区）", 36.70, 43.33, value="14.6", metric_type="actual_output", unit="千桶/日", data_date="2026年上半年平均", source="Gulf Keystone H1 2026", note="GKP直报全田半年日均；期间有停产，8月恢复后流量与半年均值不同。"),
    record("伊拉克", "Atrush", "阿特鲁什", "油田（库区）", 37.08, 44.29, value="1.2", metric_type="actual_output", unit="千桶/日", data_date="2026年第二季度平均", source="ShaMaran Q2 2026", note="全田100%口径；季度多数时间停产，7月再次停产，不能视作当前日产量。"),
    record("伊拉克", "Sarsang", "萨尔桑格", "区块（两油田）", 37.12, 44.41, value="0.7", metric_type="actual_output", unit="千桶/日", data_date="2026年第二季度平均", source="ShaMaran Q2 2026", note="Sarsang区块全额口径，包含Swara Tika与East Swara Tika两田；季度多数时间停产，不能拆为单田或视作当前日产量。坐标为区块近似点。"),
    record("伊拉克", "Swara Tika", "斯瓦拉蒂卡", "油田（Sarsang区块）", None, None, status="运营方列为生产田；当期待核", source="HKN Sarsang", note="HKN称为Sarsang区块两座生产田之一；区块0.7千桶/日的历史季度均值不可拆分。"),
    record("伊拉克", "East Swara Tika", "东斯瓦拉蒂卡", "油田（Sarsang区块）", None, None, status="运营方列为生产田；当期待核", source="HKN Sarsang", note="HKN称为Sarsang区块两座生产田之一；区块0.7千桶/日的历史季度均值不可拆分。"),
    record("伊拉克", "Khurmala", "胡尔马拉", "油田（库区）", None, None, status="2025年官方列名；当期待核", source="Kurdistan Presidency 2025", note="库区政府2025年通告明确称其为油田；未找到同田公开日均实产，坐标不臆定。"),
    record("伊拉克", "Baeshiqa", "拜什卡", "区块（试井项目）", None, None, status="DNO称2025年未生产；2024年只有试井", source="DNO Kurdistan 2025", note="DNO称2024年约5桶油当量/日来自井测试，2025年未生产；试井油当量不能填作持续区块原油日产量。"),
    record("伊拉克", "Eridu (Block 10)", "埃里杜／第十区块", "发现油田／区块", None, None, status="EITI 2023列为非生产田；后续待核", source="Iraq EITI 2023", note="EITI 2023报告表16将Eridu（Block 10）列在Dhi Qar非生产油田栏；未披露可核验商业持续日产量。"),

    record("伊拉克", "Faihaa", "费哈", "油气田", 30.7253, 47.7629, value=">100", metric_type="actual_output", unit="千桶/日", data_date="2025-09-25（报告下限）", status="运营", source="Shafaq News Faihaa", note="伊拉克石油部长称该田当日产量超过10万桶；该数为公开下限，不是精确值，也不代表当前日产量。"),
    record("伊拉克", "Fakkah", "法卡（福基）", "油田", 32.135, 47.52, metric_type="undisclosed", status="运营", source="GEM Fakkah", note="GEM列为运营油田，亦称Fauqi；未找到可核验的单田日产量。"),
    record("伊拉克", "Bazerkan", "巴泽尔坎", "油田", 31.936, 47.372, metric_type="undisclosed", status="运营", source="GEM Bazerkan", note="GEM列为运营油田，亦称Buzurgan；未找到可核验的单田日产量。"),
    record("伊拉克", "Abu Gharb", "阿布加尔卜", "油田", 32.365, 47.306, status="运营", source="GEM Abu Gharb", note="原列年度数值的原始引文未证实是该年度实际产油总量；撤回据此换算的推算日均。逐田实产待核。"),
    record("伊拉克", "Luhais", "卢海斯", "油田", 29.904, 46.952, value="89.2", metric_type="derived_daily_average", unit="千桶/日", data_date="2016年推算日均", status="EITI 2023列为生产田；当期数值待核", source="Iraq EITI 2016", note="EITI 2016报告第75页Basra Oil Company逐田年产32,631,608桶÷366日=89.2千桶/日（四舍五入）；EITI 2023表17列为生产田，但未给该田2023实产。"),
    record("伊拉克", "Subba", "苏巴", "油田", 30.258, 46.829, status="运营", value="5.8", metric_type="derived_daily_average", unit="千桶/日", data_date="2021年推算日均", source="Iraq EITI 2021", note="EITI 2021 表58（PCLD）年产2,100,000桶÷365日=5.8千桶/日（四舍五入）；历史均值，非当前日产量。"),
    record("伊拉克", "Tuba", "图巴", "油气田", 30.4036, 47.4977, value="36.2", metric_type="derived_daily_average", unit="千桶/日", data_date="2016年推算日均", status="EITI 2023列为生产田；当期数值待核", source="Iraq EITI 2016", note="EITI 2016报告第75页Basra Oil Company逐田年产13,262,897桶÷366日=36.2千桶/日（四舍五入）；EITI 2023表17列为生产田但未给该田实产。"),

    record("伊拉克", "Ajil", "阿吉勒", "油田", None, None, source="Iraq EITI 2021", note="EITI 2021表57与表58对该田年产量不一致，暂不换算日产量。"),
    record("伊拉克", "Ain Zalah", "艾因扎拉", "油田", None, None, source="Iraq EITI 2021", note="EITI 2021表57列为产油田；无近期可核验逐田日产量。"),
    record("伊拉克", "Batmah", "巴特马", "油田", None, None, source="Iraq EITI 2021", note="EITI 2021表57列为产油田；无近期可核验逐田日产量。"),
    record("伊拉克", "Hamrin", "哈姆林", "油田", None, None, source="Iraq EITI 2021", note="EITI 2021表58列为产油田；逐田当期日产量未披露。"),
    record("伊拉克", "Naft Khana", "纳夫特哈纳", "油田", None, None, status="EITI 2023列为生产田；当期数值待核", source="Iraq EITI 2023", note="EITI 2023报告表14列为Midland Oil Company生产田；报告的公司产量不可分配到该田。"),
    record("伊拉克", "Amara", "阿马拉", "油田", None, None, status="EITI 2023列为生产田；当期数值待核", source="Iraq EITI 2023", note="EITI 2023报告表15列为Maysan Oil Company生产田；公司合计量不可分配到该田。"),
    record("伊拉克", "Noor", "努尔", "油田", None, None, status="EITI 2023列为生产田；当期数值待核", source="Iraq EITI 2023", note="EITI 2023报告表15列为Maysan Oil Company生产田；公司合计量不可分配到该田。"),
    record("伊拉克", "Safiya", "萨菲亚", "油田", None, None, status="EITI 2023列为生产田；当期数值待核", source="Iraq EITI 2023", note="EITI 2023报告表13列为North Oil Company生产田；无可核验逐田日产量。"),

    # Iran
    record("伊朗", "Ahvaz", "阿瓦士", "油田", 31.32, 48.68, source="EIA Iran"),
    record("伊朗", "Marun", "马伦", "油田", 31.19, 49.08, source="GEM Marun", note="原列年度数值的原始引文未证实是该年度实际产油总量；撤回据此换算的推算日均。逐田实产待核。"),
    record("伊朗", "Aghajari", "阿加贾里", "油田", 30.70, 49.83, source="GEM Aghajari", note="原列年度数值的原始引文未证实是该年度实际产油总量；撤回据此换算的推算日均。逐田实产待核。"),
    record("伊朗", "Gachsaran", "加奇萨兰", "油田", 30.36, 50.80, source="GEM Gachsaran", note="原列年度数值的原始引文未证实是该年度实际产油总量；撤回据此换算的推算日均。逐田实产待核。"),
    record("伊朗", "Reg-e-Safid", "雷格萨菲德", "油田", 31.03, 49.31, source="EIA Iran"),
    record("伊朗", "South Azadegan", "南阿扎德甘", "油田", 30.06, 48.23, source="GEM South Azadegan", note="原列年度数值的原始引文未证实是该年度实际产油总量；撤回据此换算的推算日均。逐田实产待核。"),
    record("伊朗", "North Azadegan", "北阿扎德甘", "油田", 30.27, 48.25, value="75", metric_type="actual_output", unit="千桶/日", data_date="2019-11-25", source="Trend North Azadegan", note="Trend报道引用伊朗方面消息称日产量75千桶；这是2019年现场产量快照，不代表当前产量。"),
    record("伊朗", "Yadavaran", "雅达瓦兰", "油田", 31.03, 48.16, source="EIA Iran"),
    record("伊朗", "North Yaran", "北亚兰", "油田", 30.81, 48.14, source="EIA Iran"),
    record("伊朗", "South Yaran", "南亚兰", "油田", 30.68, 48.13, source="EIA Iran"),
    record("伊朗", "Azar", "阿扎尔", "油田", 33.08, 46.29, source="EIA Iran"),
    record("伊朗", "Darkhovin", "达尔霍温", "油田", 30.70, 48.48, source="EIA Iran"),
    record("伊朗", "Hendijan", "亨迪詹", "海上油田", 30.24, 49.70, source="EIA Iran"),
    record("伊朗", "Doroud", "多鲁德", "海上油田", 26.06, 53.04, source="EIA Iran"),
    record("伊朗", "Foroozan", "福鲁赞", "海上油田", 26.02, 52.45, source="EIA Iran"),
    record("伊朗", "Soroush", "苏鲁什", "海上油田", 29.70, 50.12, source="EIA Iran"),
    record("伊朗", "Nowruz", "诺鲁兹", "海上油田", 29.35, 50.20, source="EIA Iran"),
    record("伊朗", "Salman", "萨尔曼", "海上油气田", 25.52, 53.39, source="EIA Iran"),

    record("伊朗", "Bibi Hakimeh", "比比哈基梅", "油田", 29.91, 50.46, status="运营", source="GEM Bibi Hakimeh", note="原列年度数值的原始引文未证实是该年度实际产油总量；撤回据此换算的推算日均。逐田实产待核。"),
    record("伊朗", "Karanj", "卡兰吉", "油田", 30.9902, 49.8602, status="运营", source="GEM Karanj", note="原列年度数值的原始引文未证实是该年度实际产油总量；撤回据此换算的推算日均。逐田实产待核。"),
    record("伊朗", "Abuzar", "阿布扎尔", "海上油田", 29.292, 49.532, status="运营", source="GEM Abuzar", note="原列年度数值的原始引文未证实是该年度实际产油总量；撤回据此换算的推算日均。逐田实产待核。"),
    record("伊朗", "Mansouri", "曼苏里", "油田", 30.9289, 48.828, status="运营", source="GEM Mansouri", note="原列年度数值的原始引文未证实是该年度实际产油总量；撤回据此换算的推算日均。逐田实产待核。"),
    record("伊朗", "Sepehr-Jufair", "塞佩赫尔—朱费尔", "油田项目群", 31.298, 48.059, status="运营", source="GEM Sepehr-Jufair", note="原列年度数值的原始引文未证实是该年度实际产油总量；撤回据此换算的推算日均。逐田实产待核。"),
    record("伊朗", "Parsi", "帕西", "油田", 31.0718, 49.9237, metric_type="undisclosed", status="运营", source="GEM Parsi", note="GEM列为运营油田，属于Parsi-Paranj开发项目；项目合计量未分配给单一油田，故单田日产量留空。"),
    record("伊朗", "Bahregansar", "巴赫雷甘萨尔", "海上油田", 29.916667, 49.7, metric_type="undisclosed", status="运营", source="GEM Bahregansar", note="GEM列为运营海上油田但未给坐标；地图点位取NGA地名数据库油田点（29.916667, 49.7）作近似位置。未找到可核验的单田日产量。"),
    record("伊朗", "Sirri E", "锡里E", "海上油气田", 25.751, 54.632, status="运营", source="GEM Sirri E", note="原列年度数值的原始引文未证实是该年度实际产油总量；撤回据此换算的推算日均。逐田实产待核。"),
    record("伊朗", "Masjed Soleyman", "马斯杰德苏莱曼", "油田", 31.9325, 49.3105, status="运营", source="GEM Masjed Soleyman", note="原列年度数值的原始引文未证实是该年度实际产油总量；撤回据此换算的推算日均。逐田实产待核。"),

    # 公开地图中的位置为近似中心点，二手名录仅用于确认名称和位置，不据此填写未经核实的实产。
    record("伊朗", "Pazanan", "帕扎南", "油田", 30.4532, 50.1354, source="GEM Pazanan", note="公开资产名录；逐田持续日产量未核验。"),
    record("伊朗", "Kupal", "库帕尔", "油田", 31.3118, 49.3203, source="GEM Kupal", note="公开资产名录；逐田持续日产量未核验。"),
    record("伊朗", "Dehloran", "德赫洛兰", "油田", 32.5516, 47.1077, source="GEM Dehloran", note="公开资产名录；逐田持续日产量未核验。"),
    record("伊朗", "Paranj", "帕兰吉", "油田", 30.95, 49.85, source="GEM Paranj", note="与Parsi同属开发项目；不拆分项目合计产量。"),
    record("伊朗", "Nargesi", "纳尔格西", "油田", 29.4742, 51.2602, source="GEM Nargesi", note="公开资产名录；逐田持续日产量未核验。"),

    record("伊朗", "Hengam", "亨加姆", "跨境海上油田（伊朗侧）", None, None, value="7", metric_type="actual_output", unit="千桶/日", data_date="2010-08-24", source="SHANA Hengam 2010", note="伊朗石油部新闻报道称该日伊朗侧产量达到7,000桶/日；极旧历史快照，非2026年或伊朗—阿曼全田产量。阿曼侧与West Bukha相关。"),
    # EIA 2024列名作为伴生气收集项目的供气油田，不据项目处理能力反推油田原油量。
    record("伊朗", "Band-e-Karkheh", "班德卡尔赫", "油田", None, None, status="EIA 2024具名；当期生产状态待核", source="EIA Iran", note="EIA报告表2将其列为NGL 3200拟收集伴生气的油田；未披露该田原油日产量。"),
    record("伊朗", "West Paydar", "西帕伊达尔", "油田", None, None, status="EIA 2024具名；当期生产状态待核", source="EIA Iran", note="EIA报告表2列为NGL 3100拟接收伴生气的油田；非逐田原油数据。"),
    record("伊朗", "Chehsmeh-Khosh", "切什梅霍什", "油田", None, None, status="EIA 2024具名；当期生产状态待核", source="EIA Iran", note="按EIA报告表2英文拼法登记；伴生气处理计划不是该田原油日产量。"),
    record("伊朗", "Danan", "达南", "油田", None, None, status="EIA 2024具名；当期生产状态待核", source="EIA Iran", note="EIA报告表2列名；未披露该田原油日产量。"),
    record("伊朗", "Paydar", "帕伊达尔", "油田", None, None, status="EIA 2024具名；当期生产状态待核", source="EIA Iran", note="EIA报告表2与West Paydar分别列名；无可靠逐田日产量。"),
    record("伊朗", "Changuleh", "昌古莱", "油田", None, None, status="EIA 2024具名；当期生产状态待核", source="EIA Iran", note="EIA报告表2列名；不把伴生气收集设施容量当作原油产量。"),
    record("伊朗", "Dalpari", "达尔帕里", "油田", None, None, status="EIA 2024具名；当期生产状态待核", source="EIA Iran", note="EIA报告表2列名；逐田原油日产量未核实。"),
    record("伊朗", "South Pars", "南帕尔斯", "海上气／凝析油田", None, None, status="已开发；原油逐田值不适用", source="EIA Iran", note="EIA称为伊朗最大非伴生气田；与卡塔尔North Field同一跨境地质构造的伊朗侧，天然气和凝析油数据不作为原油实产。"),
    record("伊朗", "Darquain", "达尔昆", "油田", 30.7289, 48.2934, status="GEM列为运营；当前逐田产量未核", source="GEM Darquain", note="坐标为GEM列示WGS84位置；EIA 2024也将Darquain列入NGL 3200伴生气收集项目的供气油田名单。设施处理能力不等于该田原油产量。"),

    # Kuwait
    record("科威特", "Burgan", "布尔干", "油田", 29.05, 47.91, source="KOC / KPC"),
    record("科威特", "Magwa", "马格瓦", "油田", 29.17, 47.92, source="KOC / KPC"),
    record("科威特", "Ahmadi", "艾哈迈迪", "油田", 28.99, 48.08, source="KOC / KPC"),
    record("科威特", "Raudhatain", "劳达泰因", "油田", 30.20, 47.66, source="KOC / KPC"),
    record("科威特", "Sabriya", "萨布里亚", "油田", 30.28, 47.74, source="KOC / KPC"),
    record("科威特", "Bahra", "巴赫拉", "油田", 29.95, 47.46, source="KOC / KPC"),
    record("科威特", "Ratqa", "拉特卡", "油田", 30.13, 47.59, source="KOC / KPC"),
    record("科威特", "Umm Niqa", "乌姆尼卡", "重油田", 30.10, 47.68, value="22.14", metric_type="actual_output", unit="千桶/日", data_date="FY2023/24（日点未注明）", source="KOC Annual Report 2023-24", note="KOC年报称FY2023/24在Umm Niqa实现22,140桶/日；报告未将其定义为全年平均。"),
    record("科威特", "South Ratqa", "南拉特卡", "重油田", 30.02, 47.70, source="KOC / KPC"),
    record("科威特", "Minagish", "米纳吉什", "油田", 29.00, 46.38, source="KOC / KPC"),
    record("科威特", "Umm Gudair", "乌姆古代尔", "油田", 28.70, 46.52, source="KOC / KPC"),
    record("科威特", "Abdali", "阿卜达利", "油田", 30.03, 47.93, source="KOC / KPC"),
    record("科威特", "Wafra", "瓦夫拉", "跨境油田", 28.72, 47.90, source="KOC / KPC", note="沙特—科威特中立区共享资产。"),
    record("科威特", "Khafji", "哈夫吉", "跨境海上油田", 28.52, 48.42, source="KOC / KPC", note="沙特—科威特中立区共享资产。"),
    record("科威特", "Nokhetha", "诺赫萨", "发现海上油田", None, None, status="2024年发现；商业生产未证实", source="KOC Annual Report 2024-25", note="KOC年报的2,800桶/日是Nokhetha-1勘探井测试流量，不能填作全田持续日产量。"),
    record("科威特", "Julaiah", "朱莱亚", "发现海上油田", None, None, status="2025年发现；商业生产未证实", source="KOC Annual Report 2024-25", note="KOC年报仅披露勘探井测试与资源量，未披露全田持续日产量。"),
    record("科威特", "Mutriba", "穆特里巴", "油田", None, None, status="2025-06-15商业投产", source="KOC Mutriba", note="KOC确认轻质油商业生产；公开报道未给可核验的全田持续日产量，井测试量不作替代。"),
    record("科威特", "Shaham", "沙哈姆", "勘探油田", None, None, status="FY2024/25勘探发现；商业产量未核", source="KOC Annual Report 2024-25", note="KOC年报第30—31页称北科威特Shaham勘探田发现Zubair砂岩油藏；未给商业持续产量。"),
    record("科威特", "Kra-al-Maru", "克拉马鲁", "油田", None, None, status="FY2024/25加深井发现新储层", source="KOC Annual Report 2024-25", note="KOC年报第30—31页称在既有Kra-al-Maru油田发现Marrat储层；该发现不是全田日产量。"),

    # Qatar
    record("卡塔尔", "Al Shaheen", "阿尔沙欣", "海上油田", 26.51, 51.92, value="280.1", metric_type="actual_output", unit="千桶/日", data_date="2024年平均", source="QatarEnergy", note="QatarEnergy官方投资者演示文稿列示的2024年平均原油产量；来源直报。"),
    record("卡塔尔", "Dukhan", "杜汉", "油气田", 25.42, 50.79, value="176.4", metric_type="actual_output", unit="千桶/日", data_date="2024年平均", source="QatarEnergy", note="QatarEnergy官方投资者演示文稿列示的2024年平均原油产量；来源直报。"),
    record("卡塔尔", "Al-Rayyan", "阿尔拉扬", "海上油田", 25.98, 51.33, value="3.6", metric_type="actual_output", unit="千桶/日", data_date="2024年平均", source="QatarEnergy", note="QatarEnergy官方投资者演示文稿列示的2024年平均原油产量；来源直报。"),
    record("卡塔尔", "Al-Khaleej", "阿尔哈利杰", "海上油田", 25.70, 51.48, value="23.4", metric_type="actual_output", unit="千桶/日", data_date="2024年平均", source="QatarEnergy", note="QatarEnergy官方投资者演示文稿列示的2024年平均原油产量；来源直报。"),
    record("卡塔尔", "Idd El-Sharqi", "伊德谢尔基", "海上油田", 25.59, 51.31, value="54.4", metric_type="actual_output", unit="千桶/日", data_date="2024年平均", source="QatarEnergy", note="QatarEnergy官方投资者演示文稿列示的2024年平均原油产量；来源直报。"),
    record("卡塔尔", "Karkara", "卡尔卡拉", "海上油田", 25.46, 51.33, source="QatarEnergy"),
    record("卡塔尔", "Maydan Mahzam", "迈丹马赫赞", "海上油田", 25.20, 51.20, value="16.2", metric_type="actual_output", unit="千桶/日", data_date="2024年平均", source="QatarEnergy", note="QatarEnergy官方投资者演示文稿列示的2024年平均原油产量；来源直报。"),
    record("卡塔尔", "Bul Hanine", "布尔哈宁", "海上油田", 25.06, 51.14, value="35.1", metric_type="actual_output", unit="千桶/日", data_date="2024年平均", source="QatarEnergy", note="QatarEnergy官方投资者演示文稿列示的2024年平均原油产量；来源直报。"),
    record("卡塔尔", "Al-Murjan", "阿尔穆尔詹", "海上油田", None, None, source="QatarEnergy E&P", note="卡塔尔能源称该田通过Al-Rayyan平台生产；没有单田产量，不把Al-Rayyan平台数值分摊。"),
    record("卡塔尔", "North Field", "北方气田", "气田", 26.62, 51.45, source="QatarEnergy", note="气田，不与原油日产量比较。"),
    record("卡塔尔", "A-Structures (A-North / A-South)", "A构造（A北／A南）", "海上油田群（两个小油田）", None, None, status="2022年续签五年开发生产协议（至2027年）", source="Qatar News Agency A-Structures", note="QNA称A-North和A-South于1971年发现，A-Structures与Al-Karkara自2006年3月投产；报道的3,350万桶是三田合计累计原油，不能分配给A-Structures。单田产量及坐标未披露。"),

    # Oman
    record("阿曼", "Mukhaizna", "穆凯兹奈", "油田", 19.34, 56.47, source="Occidental Oman", note="运营商确认油田运营及累计产量，但未找到可核验的2023年单田8万桶/日实产；撤回该值。"),
    record("阿曼", "Yibal", "伊巴尔", "油田", 22.26, 56.15, source="GEM Yibal", note="原列年度数值的原始引文未证实是该年度实际产油总量；撤回据此换算的推算日均。逐田实产待核。"),
    record("阿曼", "Natih", "纳蒂赫", "油田", 22.48, 56.33, source="PDO"),
    record("阿曼", "Fahud", "法胡德", "油田", 22.35, 56.50, source="PDO"),
    record("阿曼", "Qarn Alam", "卡恩阿拉姆", "油田", 22.55, 57.07, source="PDO"),
    record("阿曼", "Marmul", "马尔穆勒", "油田", 18.12, 55.22, source="PDO"),
    record("阿曼", "Nimr", "尼姆尔", "油田", 18.76, 55.74, source="PDO"),
    record("阿曼", "Lekhwair", "莱赫韦尔", "油田", 20.59, 57.14, source="PDO"),
    record("阿曼", "Bahja", "巴赫贾", "油田", 20.96, 56.80, source="PDO"),
    record("阿曼", "Harweel", "哈维尔", "油田群", 18.08, 55.62, source="PDO"),
    record("阿曼", "Amal", "阿迈勒", "油田", 18.48, 55.72, source="PDO"),
    record("阿曼", "Zalzala", "扎尔扎拉", "油田（Harweel资产）", None, None, source="PDO Sustainability 2024", note="PDO报告第60页列Harweel 2AB项目位于Zalzala田；注气与增采累计量不是全田日均原油。"),
    record("阿曼", "Haima West", "海马西", "油田（Marmul集群）", None, None, source="PDO Sustainability 2024", note="PDO报告第60页列名；聚合物驱项目预期增采量不能转换为现时单田日产量。"),
    record("阿曼", "Al Noor", "努尔", "油田（Nimr资产）", None, None, source="PDO Sustainability 2024", note="PDO报告列Al Noor三期项目；项目增采资源量不是单田实产。"),
    record("阿曼", "Nimr-A", "尼姆尔A", "油田（Nimr资产）", None, None, source="PDO Sustainability 2024", note="PDO明确称Nimr-A油田；2024年聚合物驱投资决定的预期增采量不是已实现日产量。"),
    record("阿曼", "Nimr-E", "尼姆尔E", "油田（Nimr资产）", None, None, source="PDO Sustainability 2024", note="PDO明确称Nimr-E油田；不把Nimr资产合计量分配给该田。"),

    record("阿曼", "Budour Northeast", "布杜尔东北", "发现油田", None, None, status="发现／开发状态待核", source="PDO", note="PDO历史页面确认发现，尚无可核验的持续逐田日产量。"),

    record("阿曼", "Yumna", "尤姆纳", "海上油田", 19.9841, 58.546, value="742", metric_type="actual_output", unit="桶/日", data_date="2026年3月平均（31天生产期）", status="生产中", source="Masirah Oil Yumna", note="运营方公告称31天生产期内全田总产量日均742桶；Block 50运营方持有100%权益。"),
    record("阿曼", "Bisat", "比萨特", "油田", 21.178, 55.8542, metric_type="undisclosed", status="运营", source="OQ / GEM Bisat", note="OQ于2023年公告比萨特油田原油处理设施投产；GEM列为运营油田，逐田日产量未披露。坐标为公开地图资料的近似点。"),
    record("阿曼", "Daleel", "达利勒", "油田", 22.7241, 55.976, status="运营", source="Daleel Petroleum", note="运营商披露Block 5共有五个主要油田；区块约5万桶/日不能分配给单田。"),
    record("阿曼", "Shadi", "沙迪", "油田", None, None, status="运营", source="Daleel Petroleum", note="Block 5油田；仅有区块合计产量，单田和坐标未核验。"),
    record("阿曼", "Bushra", "布什拉", "油田", None, None, status="运营", source="Daleel Petroleum", note="Block 5油田；仅有区块合计产量，单田和坐标未核验。"),
    record("阿曼", "Mazoon", "马祖恩", "油田", None, None, status="运营", source="Daleel Petroleum", note="Block 5油田；仅有区块合计产量，单田和坐标未核验。"),
    record("阿曼", "Furat", "富拉特", "油田", None, None, status="运营", source="Daleel Petroleum", note="Block 5油田；仅有区块合计产量，单田和坐标未核验。"),
    record("阿曼", "Thahab", "扎哈卜", "油田（Block 5）", None, None, status="2023年运营商列为开采田", source="Daleel 2023", note="Daleel称近年开采Thahab；其约5万桶/日为Block 5多田总量，不分摊。"),
    record("阿曼", "Safah", "萨法", "油田", None, None, status="运营", source="Occidental Oman", note="Occidental披露Block 9的主要油田；未披露可核验单田日产量。"),
    record("阿曼", "Wadi Latham", "瓦迪拉萨姆", "油田", None, None, status="运营", source="Occidental Oman", note="Occidental披露Block 9的主要油田；未披露可核验单田日产量。"),
    record("阿曼", "Khamilah", "哈米拉", "油田", None, None, status="运营", source="Occidental Oman", note="Occidental披露Block 27油田；未披露可核验单田日产量。"),
    record("阿曼", "Wadi Aswad North", "瓦迪阿斯瓦德北", "发现油田", None, None, status="运营商列为发现；当期生产未核", source="Occidental Oman", note="Occidental列为阿曼北部发现油田；未披露可核验持续逐田日产量。"),
    record("阿曼", "Safah North B", "萨法北B", "发现油田", None, None, status="运营商列为发现；当期生产未核", source="Occidental Oman", note="Occidental列为阿曼北部发现油田；不同于Safah，未披露单田日产量。"),
    record("阿曼", "West Bukha", "西布哈", "跨境海上油田", None, None, status="运营", source="OQEP Operations", note="OQEP列为Block 8两座生产田之一；与伊朗Hengam同属跨境地质结构，未将区块合计拆为单田产量。"),
    record("阿曼", "Bukha", "布哈", "海上气田", None, None, status="运营", source="OQEP Operations", note="OQEP列为Block 8两座生产田之一；不将区块或天然气量充作单田原油日产量。"),
    record("阿曼", "Sahma", "萨赫马", "油田", None, None, status="公开列为生产田", source="OQEP Operations", note="OQEP Block 48说明列为相邻Block 7生产油田；未披露单田产量。"),
    record("阿曼", "Abu Butabul", "阿布布塔布尔", "气／凝析油田", None, None, source="OQEP Operations", note="OQEP确认Block 60油气田名称；不把Block 60油当量合计归给该田。"),
    record("阿曼", "Khazzan", "哈赞", "气田", None, None, source="OQEP Operations", note="OQEP称为Block 61阶段之一；逐田原油日产量不适用。"),
    record("阿曼", "Ghazeer", "加泽尔", "气田", None, None, source="OQEP Operations", note="OQEP称为Block 61阶段之一；逐田原油日产量不适用。"),

    # Bahrain and Yemen
    record("巴林", "Bahrain Field (Awali)", "巴林／阿瓦利油田", "油田", 26.07, 50.55, value="39.5", metric_type="actual_output", unit="千桶/日", data_date="2022年平均", source="UNFCCC Bahrain BTR", note="UNFCCC BTR列示2022年原油与凝析油年均产量39.5千桶/日。"),
    record("巴林", "Abu Safah", "阿布萨法", "跨境海上油田", 26.02, 50.61, value="300", metric_type="capacity", unit="千桶/日", data_date="网页未注明基准日（2026-09-27核对）", source="Bapco Abu Safah", note="Bapco明确为全油田30万桶/日产能，非实产；巴林与沙特权益各50%，不可按权益数推断实际日产量。"),
    record("也门", "Masila", "马西拉", "油田／14区块", 14.47, 49.54, source="Yemen Ministry of Oil", note="冲突环境下缺少可靠连续逐田日产量。"),
    record("也门", "East Shabwa", "东舍卜瓦", "油田／10区块", 14.55, 47.54, source="Yemen Ministry of Oil"),
    record("也门", "Hawareem", "哈瓦里姆", "油田／32区块", 14.32, 48.96, source="Yemen Ministry of Oil"),
    record("也门", "Alif", "阿利夫", "油田／18区块", 15.35, 45.05, source="Yemen Ministry of Oil"),
    record("也门", "Jannah", "詹纳", "油田／5区块", 15.24, 45.16, source="Yemen Ministry of Oil"),
    record("也门", "Habban", "哈班", "油田／S2（Uqlah）区块", None, None, status="2018年有原油出口记录；当前生产状态未核", source="Yemen EIA", note="EIA记载OMV在2018年从S2区块Habban田出口原油；PEPA计划提及Habban CPF。历史出口记录不代表当前持续日产量。"),
    record("也门", "Block 9 (Malik)", "9区块（马利克）", "油气区块", None, None, status="EIA记载Medco于2019年恢复区块作业；当前状态未核", source="Yemen EIA", note="区块级生产恢复信息；不能据此认定区块内每一田当期均在产或将区块产量分配给单田。"),
    record("也门", "Hiswah (Haswa)", "希斯瓦（Haswa）", "油田／Block 9", None, None, status="PEPA 2012计划列名；现行生产状态未核", source="Yemen PEPA Production Plan", note="PEPA 2012计划提到Hiswah田CPU建设，评估清单又作Haswa；按同一田名变体合并登记。区块重启不等于该田有已核实的单田产量。"),
    record("也门", "Alroidhat (Al-Rowedhat)", "阿尔罗伊达特", "油田／Block 9", None, None, status="PEPA 2012计划列名；现行生产状态未核", source="Yemen PEPA Production Plan", note="PEPA 2012计划提到Alroidhat输油管线建设，评估清单作AL-rowedhat；保留原拼法变体，未取得单田产量。"),
    record("也门", "Qarn Qeamah", "卡恩·基阿马", "油田／Block 9", None, None, status="PEPA 2012列为评估对象；商业生产未核", source="Yemen PEPA Production Plan", note="PEPA计划列入Block 9地质评估研究；名称已公开，但这不足以证明当前商业生产或单田产量。"),

    # Syria, Israel and Turkey
    record("叙利亚", "Al-Omar", "奥马尔", "油田", 35.07, 40.60, value="15", metric_type="actual_output", unit="千桶/日", data_date="2026-02-22", source="Le Monde Al-Omar 2026", note="记者实地采访运营主任称日产1.5万桶；2026-01-19较早报道约5千桶/日，修复期波动很大。"),
    record("叙利亚", "Al-Tanak", "塔纳克", "油田", 35.10, 40.34, source="Syria public reporting"),
    record("叙利亚", "Al-Jafra", "贾夫拉", "油田", 35.05, 40.47, source="Syria public reporting"),
    record("叙利亚", "Al-Ward", "瓦尔德", "油田", 35.20, 40.55, source="Syria public reporting"),
    record("叙利亚", "Al-Taym", "泰姆", "油田", 35.23, 40.26, source="Syria public reporting"),
    record("叙利亚", "Rmeilan", "鲁迈兰", "油田", 37.04, 42.03, source="Syria public reporting"),
    record("叙利亚", "Suwaydiya", "苏韦迪耶", "油田", 37.07, 41.93, source="Syria public reporting"),
    record("叙利亚", "Qarachok", "卡拉乔克", "油田（Rmeilan Sector One）", None, None, status="2026年Rudaw列为Sector One油田；单田状态待核", source="Rudaw Rmeilan Sector One", note="Rudaw列为鲁迈兰Sector One八个油田之一；报道中的区域日产量与产能是全区合计，不拆给单田。"),
    record("叙利亚", "Hamza", "哈姆扎", "油田（Rmeilan Sector One）", None, None, status="2026年Rudaw列为Sector One油田；单田状态待核", source="Rudaw Rmeilan Sector One", note="Rudaw列为鲁迈兰Sector One油田；报道中的区域总产能及当期产量不能分配给单田。"),
    record("叙利亚", "Alyan", "阿利扬", "油田（Rmeilan Sector One）", None, None, status="2026年Rudaw列为Sector One油田；单田状态待核", source="Rudaw Rmeilan Sector One", note="Rudaw列为鲁迈兰Sector One油田；报道中的区域总产能及当期产量不能分配给单田。"),
    record("叙利亚", "Sazabeh", "萨扎贝", "油田（Rmeilan Sector One）", None, None, status="2026年Rudaw列为Sector One油田；单田状态待核", source="Rudaw Rmeilan Sector One", note="Rudaw列为鲁迈兰Sector One油田；报道中的区域总产能及当期产量不能分配给单田。"),
    record("叙利亚", "Ode", "奥德", "油田（Rmeilan Sector One）", None, None, status="2026年Rudaw列为Sector One油田；单田状态待核", source="Rudaw Rmeilan Sector One", note="Rudaw列为鲁迈兰Sector One油田；报道中的区域总产能及当期产量不能分配给单田。"),
    record("叙利亚", "Tigris", "底格里斯", "油田（Rmeilan Sector One）", None, None, status="2026年Rudaw列为Sector One油田；单田状态待核", source="Rudaw Rmeilan Sector One", note="Rudaw列为鲁迈兰Sector One油田；报道中的区域总产能及当期产量不能分配给单田。"),
    record("以色列", "Heletz", "赫莱兹", "油田", 31.57, 34.62, source="Israel Ministry of Energy", note="当前实际产量和停产状态未获可靠公开确认。"),
    record("以色列", "Meged", "梅格德", "油田", 32.28, 35.03, source="Israel Ministry of Energy"),
    record("以色列", "Leviathan", "利维坦", "气田", 32.58, 34.78, source="Israel Ministry of Energy", note="气田。"),
    record("以色列", "Tamar", "塔马尔", "气田", 31.99, 34.33, source="Israel Ministry of Energy", note="气田。"),
    record("以色列", "Karish", "卡里什", "气田", 32.62, 33.94, source="Israel Ministry of Energy", note="气田。"),
    record("以色列", "Tanin", "塔宁", "气田", 32.73, 34.10, source="Israel Ministry of Energy", note="气田。"),
    record("土耳其", "Raman", "拉曼", "油田", 37.86, 41.16, source="TPAO"),
    record("土耳其", "Batı Raman", "西拉曼", "油田", 37.88, 41.05, source="TPAO"),
    record("土耳其", "Garzan", "加尔赞", "油田", 37.75, 41.45, source="TPAO"),
    record("土耳其", "Şelmo", "谢尔莫", "油田", 37.77, 41.69, source="TPAO"),
    record("土耳其", "Gabar", "加巴尔", "油田群", 37.40, 42.45, source="TPAO"),

    # Egypt: named assets from a 2013 operator report and EGPC's 2023 brownfields package.
    record("埃及", "Belayim", "贝莱伊姆", "油田", None, None, value="105", metric_type="actual_output", unit="千桶/日", data_date="2013年", status="2013年运营商报告产量；当前值未核", source="Eni Egypt Factbook 2013", note="Eni报告2013年Belayim约105千桶/日，并列其净额56千桶/日；这是历史数据，不代表当前田级实产。"),
    record("埃及", "Shukheir Offshore (Shukheir Bay)", "舒凯尔海上（舒凯尔湾）", "油田／EGPC棕地招标资产", None, None, status="EGPC 2023棕地资料列名；当前逐田实产未核", source="Egypt EGPC Brownfields 2023", note="EGPC图示资产面积5平方公里；面积不是储量或产量。"),
    record("埃及", "Shukheir Offshore (Gamma)", "舒凯尔海上（伽马）", "油田／EGPC棕地招标资产", None, None, status="EGPC 2023棕地资料列名；当前逐田实产未核", source="Egypt EGPC Brownfields 2023", note="EGPC图示资产面积23.7平方公里；面积不是储量或产量。"),
    record("埃及", "Gazwarina", "加兹瓦里纳", "油田／EGPC棕地招标资产", None, None, status="EGPC 2023棕地资料列名；当前逐田实产未核", source="Egypt EGPC Brownfields 2023", note="EGPC图示资产面积2.5平方公里；面积不是储量或产量。"),
    record("埃及", "Ras El Ush", "拉斯埃尔乌什", "油田／EGPC棕地招标资产", None, None, status="EGPC 2023棕地资料列名；当前逐田实产未核", source="Egypt EGPC Brownfields 2023", note="EGPC图示资产面积9平方公里；面积不是储量或产量。"),
    record("埃及", "Zeit Bay", "宰特湾", "油田／EGPC棕地招标资产", None, None, status="EGPC 2023棕地资料列名；当前逐田实产未核", source="Egypt EGPC Brownfields 2023", note="EGPC图示资产面积38平方公里；面积不是储量或产量。"),
    record("埃及", "Ras Budran", "拉斯布德兰", "油田／EGPC棕地招标资产", None, None, status="EGPC 2023棕地资料列名；当前逐田实产未核", source="Egypt EGPC Brownfields 2023", note="EGPC图示资产面积15平方公里；面积不是储量或产量。"),
    record("埃及", "East Zeit (E. Zeit)", "东宰特（E. Zeit）", "油田／EGPC棕地招标资产", None, None, status="EGPC 2023棕地资料列名；当前逐田实产未核", source="Egypt EGPC Brownfields 2023", note="EGPC图示资产面积27平方公里；面积不是储量或产量。"),
    record("埃及", "Ashrafi", "阿什拉菲", "油田／EGPC棕地招标资产", None, None, status="EGPC 2023棕地资料列名；当前逐田实产未核", source="Egypt EGPC Brownfields 2023", note="EGPC图示资产面积35平方公里；面积不是储量或产量。"),
    record("埃及", "Wadi El Sahl Development Area", "瓦迪埃尔萨赫勒开发区", "油田开发区／EGPC棕地招标资产", None, None, status="EGPC 2023棕地资料列名；田级产量待核", source="Egypt EGPC Brownfields 2023", note="原资料称Development Area并列面积31平方公里，目录按开发区记录，不将其强行当作单一油田；EGPC包件的剩余储量／增产潜力不拆给单个资产。"),
]
