"""经过口径审计的中东公开命名油气资产目录（DEMO）。

设计原则：一个记录对应一个可公开识别的油田、气田、区块或项目；
未公开的逐田数值保留为空，不以国家/油田群数据填充。
坐标为公开地图资料交叉核对后的近似中心点，不能替代运营商海图或井位坐标。
"""

from __future__ import annotations

from typing import Any


SOURCES = {
    "ADNOC Onshore": "https://www.adnoc.ae/en/adnoc-onshore/about-us/what-we-do",
    "ADNOC Offshore": "https://www.adnoc.ae/en/adnoc-offshore",
    "ADNOC Al Yasat": "https://adnoc.ae/en/al-yasat-petroleum/about-us/what-we-do",
    "ADNOC Ghasha": "https://adnoc.ae/en/news-and-media/press-releases/2025/uae-president-chairs-adnoc-board-of-directors-meeting-at-habshan-complex",
    "Dubai Petroleum": "https://www.dubaipetroleum.ae/about-us/oil-and-gas-assets/",
    "Saudi Aramco / EIA": "https://www.eia.gov/international/analysis/country/SAU",
    "EIA Iran": "https://www.eia.gov/international/content/analysis/countries_long/Iran/pdf/Iran%20CAB%202024.pdf",
    "EIA Iraq": "https://www.eia.gov/international/analysis/country/irq",
    "KOC / KPC": "https://www.kockw.com/sites/EN/Pages/Profile/whoAreWe/KOC-History.aspx",
    "QatarEnergy": "https://www.qatarenergy.qa/en/MediaCenter/Publications/QatarEnergy_Investors_Presentation_November_2025.pdf",
    "PDO": "https://www.pdo.co.om/en/Pages/WhoWeAre/OurJourney.aspx",
    "Bapco": "https://www.bapco.net/en/page/history/",
    "Yemen Ministry of Oil": "https://mom-ye.com/site-en/",
    "Syria public reporting": "https://www.reuters.com/business/energy/shell-seeks-exit-syrias-al-omar-oilfield-official-says-2026-01-19/",
    "Le Monde Al-Omar 2026": "https://www.lemonde.fr/en/economy/article/2026/02/22/the-syrian-oil-sector-s-year-zero_6750756_19.html",
    "Israel Ministry of Energy": "https://prime.energy.gov.il/en/prime.html",
    "UNFCCC Bahrain BTR": "https://unfccc.int/sites/default/files/resource/30112025_Bahrain%27s_BTR1_2024_to_the_UNFCCC_vSubmitted.pdf",
    "KOC Annual Report 2023-24": "https://www.kockw.com/sites/EN/Annual%20Reports/2023%20-%202024%20English.pdf",
    "Masirah Oil Yumna": "https://www.masirahoil.om/post/production-update-march-2026",
    "GEM Yibal": "https://www.gem.wiki/Yibal_Oil_and_Gas_Field_(Oman)",
    "OQ / GEM Bisat": "https://oq.com/en/news-and-media/newsroom/20230126-oq-celebrates-inauguration-of-bisat-oil-field",
    "Shafaq News Faihaa": "https://shafaq.com/en/Economy/Iraq-expands-oil-production-starts-drilling-in-border-region",
    "Iraqi News West Qurna-1": "https://www.iraqinews.com/iraq/iraq-to-raise-west-qurna-1s-output-to-670000-bpd-in-2026/",
    "GEM Fakkah": "https://www.gem.wiki/Fakkah_Oil_Field_(Iraq)",
    "GEM Bazerkan": "https://www.gem.wiki/Bazerkan_Oil_Field_(Iraq)",
    "GEM Abu Gharb": "https://www.gem.wiki/Abu_Gharb_Oil_Field_(Iraq)",
    "GEM Luhais": "https://www.gem.wiki/Luhais_Oil_Field_(Iraq)",
    "GEM Subba": "https://www.gem.wiki/Subba_Oil_Field_(Iraq)",
    "GEM Tuba": "https://www.gem.wiki/Tuba_Oil_and_Gas_Field_(Iraq)",
    "GEM Bibi Hakimeh": "https://www.gem.wiki/Bibi_Hakimeh_Oil_Field_(Iran)",
    "GEM Karanj": "https://www.gem.wiki/Karanj_Oil_Field_(Iran)",
    "GEM Abuzar": "https://www.gem.wiki/Abuzar_Oil_Field_(Iran)",
    "GEM Mansouri": "https://www.gem.wiki/Mansouri_Oil_Field_(Iran)",
    "GEM Sepehr-Jufair": "https://www.gem.wiki/Sepehr-Jufair_Oil_Field_(Iran)",
    "GEM Parsi": "https://www.gem.wiki/Parsi_Oil_Field_(Iran)",
    "GEM Bahregansar": "https://www.gem.wiki/Bahregansar_Oil_Field_(Iran)",
    "GEM Sirri E": "https://www.gem.wiki/Sirri_E_Oil_and_Gas_Field_(Iran)",
    "GEM Masjed Soleyman": "https://www.gem.wiki/Masjed_Soleyman_Oil_Field_(Iran)",
    "GEM Marun": "https://www.gem.wiki/Marun_Oil_Field_(Iran)",
    "GEM Aghajari": "https://www.gem.wiki/Aghajari_Oil_Field_(Iran)",
    "GEM Gachsaran": "https://www.gem.wiki/Gachsaran_Oil_and_Gas_Field_(Iran)",
    "GEM South Azadegan": "https://www.gem.wiki/Azadegan_South_Oil_Field_(Iran)",
    "Trend North Azadegan": "https://www.trend.az/iran/business/3153217.html",
    "TPAO": "https://www.tpao.gov.tr/",
    "Rumaila Operating Organisation": "https://rumaila.iq/english/about-us/history-2/",
    "DNO 2025 Results": "https://www.dno.no/media/t14pl1zl/2025-interim-results-report.pdf",
    "Gulf Keystone H1 2026": "https://www.gulfkeystone.com/2026-half-year-results-announcement/",
    "ShaMaran Q2 2026": "https://shamaranpetroleum.com/news/shamaran-reports-second-quarter-2026-results-122891/",
    "PETRONAS Gharraf": "https://www.petronas.com/partner-us/pcihbv-contract-plan",
    "KOC Annual Report 2024-25": "https://www.kockw.com/sites/EN/Annual%20Reports/2024-2025%20English.pdf",
    "Saudi Press Agency 2025": "https://www.spa.gov.sa/en/N2295070",
    "Saudi Press Agency 2024": "https://www.spa.gov.sa/N2131725",
    "Daleel Petroleum": "https://daleelpetroleum.com/operational-excellence/production",
    "Occidental Oman": "https://www.oxy.com/operations/performance-production/",
    "GEM Pazanan": "https://www.gem.wiki/Pazanan_Oil_Field_(Iran)",
    "GEM Kupal": "https://www.gem.wiki/Kupal_Oil_Field_(Iran)",
    "GEM Dehloran": "https://www.gem.wiki/Dehloran_Oil_Field_(Iran)",
    "GEM Paranj": "https://www.gem.wiki/Paranj_Oil_Field_(Iran)",
    "GEM Nargesi": "https://www.gem.wiki/Nargesi_Oil_Field_(Iran)",
}


def record(
    country: str,
    name: str,
    name_cn: str,
    asset_type: str,
    lat: float | None,
    lon: float | None,
    *,
    value: str | None = None,
    metric_type: str = "undisclosed",
    unit: str | None = None,
    data_date: str | None = None,
    status: str = "公开命名资产",
    source: str,
    note: str = "",
) -> dict[str, Any]:
    return {
        "country": country,
        "name": name,
        "name_cn": name_cn,
        "asset_type": asset_type,
        "lat": lat,
        "lon": lon,
        "value": value,
        "metric_type": metric_type,
        "unit": unit,
        "data_date": data_date,
        "status": status,
        "coordinate_precision": "近似中心点" if lat is not None and lon is not None else "待核验；仅列目录",
        "source": source,
        "source_url": SOURCES[source],
        "note": note,
    }


# 仅在来源给出明确的字段级口径时填写 value；None 表示尚无可核验的字段级公开值。
ASSETS = [
    # Saudi Arabia
    record("沙特阿拉伯", "Ghawar", "加瓦尔", "油田", 25.42, 49.57, value="3,800", metric_type="maximum_sustainable_capacity", unit="千桶/日", data_date="2018-12-31", source="Saudi Aramco / EIA", note="最大可持续产能，不是当期实际产量。"),
    record("沙特阿拉伯", "Safaniya", "萨法尼亚", "海上油田", 28.18, 48.78, source="Saudi Aramco / EIA"),
    record("沙特阿拉伯", "Khurais", "库赖斯", "油田", 25.03, 48.24, source="Saudi Aramco / EIA"),
    record("沙特阿拉伯", "Shaybah", "谢拜", "油田", 22.48, 53.78, value="1,000", metric_type="capacity", unit="千桶/日", data_date="2016-01-01", source="Saudi Aramco / EIA", note="公开长期产能，非最新实际日产量。"),
    record("沙特阿拉伯", "Manifa", "马尼法", "海上油田", 27.62, 49.87, source="Saudi Aramco / EIA"),
    record("沙特阿拉伯", "Marjan", "马尔詹", "海上油田", 27.47, 49.86, value="300", metric_type="incremental_capacity", unit="千桶/日", data_date="2025-12-31", source="Saudi Aramco / EIA", note="新增产能，不是油田总产量。"),
    record("沙特阿拉伯", "Berri", "贝里", "海上油田", 27.83, 49.93, value="250", metric_type="incremental_capacity", unit="千桶/日", data_date="2025-12-31", source="Saudi Aramco / EIA", note="新增产能，不是油田总产量。"),
    record("沙特阿拉伯", "Zuluf", "祖卢夫", "海上油田", 27.67, 49.12, value="600", metric_type="incremental_capacity", unit="千桶/日", data_date="2026-12-31", source="Saudi Aramco / EIA", note="项目处理能力目标。"),
    record("沙特阿拉伯", "Qatif", "卡提夫", "油田", 26.55, 50.01, source="Saudi Aramco / EIA"),
    record("沙特阿拉伯", "Abqaiq", "阿布盖格", "油田", 25.94, 49.68, source="Saudi Aramco / EIA"),
    record("沙特阿拉伯", "Khursaniyah", "胡尔萨尼亚", "油田", 27.72, 48.91, source="Saudi Aramco / EIA"),
    record("沙特阿拉伯", "Dammam", "达曼", "油田", 26.36, 49.99, value="25", metric_type="incremental_capacity", unit="千桶/日", data_date="2024-12-31", source="Saudi Aramco / EIA"),
    record("沙特阿拉伯", "Jafurah", "贾富拉", "非常规气田", 25.43, 48.82, metric_type="undisclosed", source="Saudi Aramco / EIA", note="天然气项目，不纳入原油日产量比较。"),
    # 2025 年公布的新发现：井测试流量不是油田持续日产量；未核验点位不绘地图标。
    record("沙特阿拉伯", "Jabu", "贾布", "发现油田", None, None, status="已发现；商业生产未证实", source="Saudi Press Agency 2025", note="官方公布的新发现油田；试井流量不填作油田日产量。"),
    record("沙特阿拉伯", "Sayahid", "萨亚希德", "发现油田", None, None, status="已发现；商业生产未证实", source="Saudi Press Agency 2025", note="官方公布的新发现油田；逐田实产未披露。"),
    record("沙特阿拉伯", "Ayfan", "艾凡", "发现油田", None, None, status="已发现；商业生产未证实", source="Saudi Press Agency 2025", note="官方公布的新发现油田；逐田实产未披露。"),
    record("沙特阿拉伯", "Nuwayr", "努韦尔", "发现油田", None, None, status="已发现；商业生产未证实", source="Saudi Press Agency 2025", note="官方公布的新发现油田；逐田实产未披露。"),
    record("沙特阿拉伯", "Damda", "达姆达", "发现油田", None, None, status="已发现；商业生产未证实", source="Saudi Press Agency 2025", note="官方公布的新发现油田；逐田实产未披露。"),
    record("沙特阿拉伯", "Qurqas", "古尔加斯", "发现油田", None, None, status="已发现；商业生产未证实", source="Saudi Press Agency 2025", note="官方公布的新发现油田；逐田实产未披露。"),
    record("沙特阿拉伯", "Ladam", "拉达姆", "非常规发现油田", None, None, status="2024年发现；商业生产未证实", source="Saudi Press Agency 2024", note="官方公布的非常规油田；5,100桶/日是Ladam-2井测试流量，不是全田持续日产量。"),
    record("沙特阿拉伯", "Faruq", "法鲁克", "非常规发现油田", None, None, status="2024年发现；商业生产未证实", source="Saudi Press Agency 2024", note="官方公布的非常规油田；4,557桶/日是Faruq-4井测试流量，不是全田持续日产量。"),

    # United Arab Emirates — ADNOC Onshore
    record("阿联酋", "Bab", "巴布", "油田", 23.93, 53.79, value="450", metric_type="capacity", unit="千桶/日", data_date="2020-12-31", source="ADNOC Onshore", note="公开产能口径；不是当期实际日产量。"),
    record("阿联酋", "Bu Hasa", "布哈萨", "油田", 23.52, 53.24, value="650", metric_type="capacity", unit="千桶/日", data_date="2024-11-05", source="ADNOC Onshore", note="维持/设计产能口径。"),
    record("阿联酋", "Huwaila", "胡韦拉", "油田", 23.70, 53.45, source="ADNOC Onshore"),
    record("阿联酋", "Bida Al-Qemzan", "比达·盖姆赞", "油田", 23.66, 53.66, source="ADNOC Onshore"),
    record("阿联酋", "Al Dabb'iya", "达比亚", "油田", 24.36, 54.15, source="ADNOC Onshore"),
    record("阿联酋", "Rumaitha", "鲁迈萨", "油田", 24.30, 54.22, source="ADNOC Onshore"),
    record("阿联酋", "Shanayel", "沙奈耶勒", "油田", 24.18, 54.27, source="ADNOC Onshore"),
    record("阿联酋", "Asab", "阿萨布", "油田", 23.45, 53.77, source="ADNOC Onshore"),
    record("阿联酋", "Sahil", "萨希勒", "油田", 23.55, 53.90, source="ADNOC Onshore"),
    record("阿联酋", "Shah", "沙阿", "油气田", 22.99, 53.95, value="70", metric_type="oil_capacity", unit="千桶/日", data_date="2025-01-01", source="ADNOC Onshore", note="油产能；与 Shah 气体处理能力分开。"),
    record("阿联酋", "Qusahwira", "古萨赫维拉", "油田", 23.23, 54.18, source="ADNOC Onshore"),
    record("阿联酋", "Mender", "门德尔", "油田", 23.08, 54.00, source="ADNOC Onshore"),
    record("阿联酋", "Jumaylah", "朱迈拉", "油田", 24.05, 53.70, status="公开命名；生产状态待确认", source="ADNOC Onshore"),
    record("阿联酋", "Al Nouf", "努夫", "油田", 24.11, 53.82, status="公开命名；生产状态待确认", source="ADNOC Onshore"),

    # United Arab Emirates — ADNOC Offshore
    record("阿联酋", "Upper Zakum", "上扎库姆", "海上油田", 24.85, 53.66, value="1,000", metric_type="capacity", unit="千桶/日", data_date="2024-01-01", source="ADNOC Offshore", note="产能基线，不是实际日产量。"),
    record("阿联酋", "Lower Zakum", "下扎库姆", "海上油田", 24.74, 53.51, value="450", metric_type="capacity", unit="千桶/日", data_date="2025-12-31", source="ADNOC Offshore"),
    record("阿联酋", "Umm Shaif", "乌姆沙伊夫", "海上油田", 25.26, 53.28, value="275", metric_type="capacity", unit="千桶/日", data_date="2024-01-01", source="ADNOC Offshore"),
    record("阿联酋", "Satah", "萨塔赫", "海上油田", 25.10, 52.74, source="ADNOC Offshore"),
    record("阿联酋", "Nasr", "纳斯尔", "海上油田", 25.54, 53.52, value="65", metric_type="historical_capacity", unit="千桶/日", data_date="2017-01-01", source="ADNOC Offshore", note="历史设计口径，不能视为当前实际日产量。"),
    record("阿联酋", "Umm Al Dalkh", "乌姆阿尔达尔赫", "海上油田", 24.63, 54.10, source="ADNOC Offshore"),
    record("阿联酋", "Satah Al Razboot (SARB)", "萨塔赫·阿尔拉兹布特", "海上油气田", 25.19, 53.18, value="140", metric_type="capacity", unit="千桶/日", data_date="2024-07-30", source="ADNOC Offshore", note="油产能；深层气项目单独记录。"),
    record("阿联酋", "Umm Lulu", "乌姆卢卢", "海上油田", 24.70, 54.06, value="105", metric_type="historical_design_capacity", unit="千桶/日", data_date="2017-01-01", source="ADNOC Offshore", note="历史设计值，不是当前实际日产量。"),
    record("阿联酋", "Abu Al Bukhoosh", "阿布阿尔布胡什", "海上油田", 25.50, 53.15, source="ADNOC Offshore"),

    # United Arab Emirates — Al Yasat / Ghasha / other concessions
    record("阿联酋", "Bu Haseer", "布哈塞尔", "海上油田", 24.93, 53.17, value="15", metric_type="target_capacity", unit="千桶/日", data_date="2018-03-01", source="ADNOC Al Yasat", note="全油田目标；早期生产为8千桶/日。"),
    record("阿联酋", "Belbazem", "贝尔巴泽姆", "海上油田", 25.13, 53.59, value="45", metric_type="target_capacity", unit="千桶/日", data_date="2023-03-27", source="ADNOC Al Yasat", note="区块达产能力。"),
    record("阿联酋", "Umm Al Salsal", "乌姆阿尔萨尔萨勒", "海上油田", 25.07, 53.53, source="ADNOC Al Yasat"),
    record("阿联酋", "Umm Al Dholou", "乌姆阿尔祖卢", "海上油田", 25.01, 53.64, source="ADNOC Al Yasat"),
    record("阿联酋", "Arzanah", "阿尔扎纳", "海上油田", 24.79, 52.56, source="ADNOC Al Yasat"),
    record("阿联酋", "Nahaidiin", "纳海迪因", "油田", 23.82, 52.20, source="ADNOC Al Yasat"),
    record("阿联酋", "Bin Hadi", "本哈迪", "油田", 23.72, 52.43, source="ADNOC Al Yasat"),
    record("阿联酋", "Gezira", "盖济拉", "油田", 23.89, 52.61, source="ADNOC Al Yasat"),
    record("阿联酋", "Muhaymat", "穆海马特", "浅海油田", 24.10, 52.10, source="ADNOC Al Yasat"),
    record("阿联酋", "Sila", "锡拉", "浅海油田", 24.08, 51.76, source="ADNOC Al Yasat"),
    record("阿联酋", "Ghasha", "加沙", "超酸性气田", 24.95, 52.77, source="ADNOC Ghasha"),
    record("阿联酋", "Dalma", "达尔马", "超酸性气田", 24.78, 52.83, source="ADNOC Ghasha"),
    record("阿联酋", "Shuweihat", "舒韦哈特", "超酸性气田", 24.20, 52.55, source="ADNOC Ghasha"),
    record("阿联酋", "SARB Deep Gas", "SARB 深层气项目", "天然气项目", 25.19, 53.18, value="200", metric_type="target_capacity", unit="百万标准立方英尺/日", data_date="2026-01-07", source="ADNOC Ghasha", note="天然气项目，不能与原油日产量相加。"),
    record("阿联酋", "Hail (ADOC)", "海尔（ADOC）", "海上油田", 24.37, 53.41, value="21", metric_type="historical_peak", unit="千桶/日", data_date="2018-01-01", source="ADNOC Ghasha", note="同名资产须以运营商和坐标去重；此为历史口径。"),
    record("阿联酋", "Mubarraz", "穆巴拉兹", "海上油田", 24.40, 53.52, source="ADNOC Ghasha"),
    record("阿联酋", "Umm Al-Anbar", "乌姆阿尔安巴尔", "海上油田", 24.30, 53.45, source="ADNOC Ghasha"),
    record("阿联酋", "Neewat Al-Ghalan", "尼瓦特阿尔加兰", "海上油田", 24.22, 53.55, source="ADNOC Ghasha"),
    record("阿联酋", "Bunduq", "本杜克", "跨境海上油田", 25.22, 52.72, source="ADNOC Offshore"),
    record("阿联酋", "Haliba", "哈利巴", "油田", 23.00, 53.80, value="40", metric_type="target_capacity", unit="千桶/日", data_date="2019-06-01", source="ADNOC Onshore", note="初期生产约10千桶/日；40为目标产能。"),
    record("阿联酋", "Fateh", "法泰赫", "海上油田", 25.54, 54.29, source="Dubai Petroleum"),
    record("阿联酋", "South-West Fateh", "西南法泰赫", "海上油田", 25.45, 54.19, source="Dubai Petroleum"),
    record("阿联酋", "Falah", "法拉赫", "海上油田", 25.63, 54.21, source="Dubai Petroleum"),
    record("阿联酋", "Rashid", "拉希德", "海上油田", 25.45, 54.40, source="Dubai Petroleum"),
    record("阿联酋", "Jalilah", "贾利拉", "海上油田", 25.38, 54.34, source="Dubai Petroleum"),
    record("阿联酋", "Margham", "马尔格姆", "凝析油气田", 24.98, 55.61, value="25", metric_type="historical_condensate_output", unit="千桶/日", data_date="2010-12-31", source="Dubai Petroleum", note="2010年凝析油，非当前原油日产量。"),
    record("阿联酋", "Bab Gas Cap", "巴布气顶项目", "天然气项目", 23.93, 53.79, value="1,500", metric_type="target_capacity", unit="百万标准立方英尺/日", data_date="2026-01-01", source="ADNOC Onshore", note="天然气项目。"),
    record("阿联酋", "Ruwais Diyab", "鲁韦斯迪亚布", "非常规气特许权", 24.15, 52.70, source="ADNOC Ghasha", note="特许权，不是单一油田。"),

    # Iraq
    record("伊拉克", "Rumaila", "鲁迈拉", "油田", 30.08, 47.43, value="1,370", metric_type="actual_output", unit="千桶/日", data_date="2025年平均", source="Rumaila Operating Organisation", note="运营组织直报2025全年日均137万桶；不是当前瞬时日产量。"),
    record("伊拉克", "West Qurna-1", "西古尔纳一期", "油田", 30.77, 47.25, value="600", metric_type="actual_output", unit="千桶/日", data_date="2025-11-20", source="Iraqi News West Qurna-1", note="报道引用油田管理方称当日产量为600千桶/日；旧750千桶/日记录是产能，2026年实际日产量未核实。"),
    record("伊拉克", "West Qurna-2", "西古尔纳二期", "油田", 30.96, 47.31, source="EIA Iraq", note="原列2025-12-08的46万桶/日无对应EIA逐田实产证据；当日管线事故停产，故撤回该日期数值。"),
    record("伊拉克", "Zubair", "祖拜尔", "油田", 30.20, 47.82, source="EIA Iraq"),
    record("伊拉克", "Majnoon", "马季努恩", "油田", 31.05, 47.72, source="EIA Iraq"),
    record("伊拉克", "Halfaya", "哈法亚", "油田", 31.58, 47.30, source="EIA Iraq"),
    record("伊拉克", "Gharraf", "加拉夫", "油田", 31.45, 46.78, value="130", metric_type="actual_output", unit="千桶/日", data_date="截至2022-04-20的运营资料", source="PETRONAS Gharraf", note="PETRONAS资料称该田平均约13万桶/日；网页给出2022-04-20累计出口基准日，属于历史资料。"),
    record("伊拉克", "Badra", "巴德拉", "油田", 33.03, 45.03, source="EIA Iraq"),
    record("伊拉克", "Ahdab", "阿赫达卜", "油田", 32.99, 44.63, source="EIA Iraq"),
    record("伊拉克", "East Baghdad", "东巴格达", "油田", 33.45, 44.60, source="EIA Iraq"),
    record("伊拉克", "Nahr Umar", "纳赫尔乌马尔", "油田", 30.40, 47.72, source="EIA Iraq"),
    record("伊拉克", "Artawi", "阿尔塔维", "油田", 30.42, 47.91, source="EIA Iraq"),
    record("伊拉克", "Nassiriya", "纳西里耶", "油田", 31.12, 46.27, source="EIA Iraq"),
    record("伊拉克", "Kirkuk", "基尔库克", "油田", 35.47, 44.39, source="EIA Iraq"),
    record("伊拉克", "Bai Hassan", "拜哈桑", "油田", 35.61, 44.40, source="EIA Iraq"),
    record("伊拉克", "Jambur", "詹布尔", "油田", 35.31, 44.48, source="EIA Iraq"),
    record("伊拉克", "Khabbaz", "哈巴兹", "油田", 35.52, 44.21, source="EIA Iraq"),
    record("伊拉克", "Qayyarah", "盖亚拉", "油田", 35.80, 43.31, source="EIA Iraq"),
    record("伊拉克", "Najma", "纳杰马", "油田", 35.91, 43.20, source="EIA Iraq"),
    record("伊拉克", "Tawke", "陶凯", "油田（库区）", 37.02, 43.27, value="29.095", metric_type="actual_output", unit="千桶/日", data_date="2025年第四季度平均", source="DNO 2025 Results", note="DNO直报全田总产量；不是DNO的75%权益产量。"),
    record("伊拉克", "Peshkabir", "佩什卡比尔", "油田（库区）", 37.13, 43.47, value="48.173", metric_type="actual_output", unit="千桶/日", data_date="2025年第四季度平均", source="DNO 2025 Results", note="DNO直报全田总产量；不是DNO的75%权益产量。"),
    record("伊拉克", "Taq Taq", "塔克塔克", "油田（库区）", 35.91, 44.62, source="EIA Iraq"),
    record("伊拉克", "Shaikan", "沙伊坎", "油田（库区）", 36.70, 43.33, value="14.6", metric_type="actual_output", unit="千桶/日", data_date="2026年上半年平均", source="Gulf Keystone H1 2026", note="GKP直报全田半年日均；期间有停产，8月恢复后流量与半年均值不同。"),
    record("伊拉克", "Atrush", "阿特鲁什", "油田（库区）", 37.08, 44.29, value="1.2", metric_type="actual_output", unit="千桶/日", data_date="2026年第二季度平均", source="ShaMaran Q2 2026", note="全田100%口径；季度多数时间停产，7月再次停产，不能视作当前日产量。"),
    record("伊拉克", "Sarsang", "萨尔桑格", "油田（库区）", 37.12, 44.41, value="0.7", metric_type="actual_output", unit="千桶/日", data_date="2026年第二季度平均", source="ShaMaran Q2 2026", note="全田100%口径；季度多数时间停产，7月再次停产，不能视作当前日产量。"),

    record("伊拉克", "Faihaa", "费哈", "油气田", 30.7253, 47.7629, value=">100", metric_type="actual_output", unit="千桶/日", data_date="2025-09-25（报告下限）", status="运营", source="Shafaq News Faihaa", note="伊拉克石油部长称该田当日产量超过10万桶；该数为公开下限，不是精确值，也不代表当前日产量。"),
    record("伊拉克", "Fakkah", "法卡（福基）", "油田", 32.135, 47.52, metric_type="undisclosed", status="运营", source="GEM Fakkah", note="GEM列为运营油田，亦称Fauqi；未找到可核验的单田日产量。"),
    record("伊拉克", "Bazerkan", "巴泽尔坎", "油田", 31.936, 47.372, metric_type="undisclosed", status="运营", source="GEM Bazerkan", note="GEM列为运营油田，亦称Buzurgan；未找到可核验的单田日产量。"),
    record("伊拉克", "Abu Gharb", "阿布加尔卜", "油田", 32.365, 47.306, status="运营", source="GEM Abu Gharb", note="原列年度数值的原始引文未证实是该年度实际产油总量；撤回据此换算的推算日均。逐田实产待核。"),
    record("伊拉克", "Luhais", "卢海斯", "油田", 29.904, 46.952, status="运营", source="GEM Luhais", note="原列年度数值的原始引文未证实是该年度实际产油总量；撤回据此换算的推算日均。逐田实产待核。"),
    record("伊拉克", "Subba", "苏巴", "油田", 30.258, 46.829, status="运营", source="GEM Subba", note="原列年度数值的原始引文未证实是该年度实际产油总量；撤回据此换算的推算日均。逐田实产待核。"),
    record("伊拉克", "Tuba", "图巴", "油气田", 30.4036, 47.4977, value="36.2", metric_type="derived_daily_average", unit="千桶/日", data_date="2016年推算日均（13.26百万桶÷366日）", status="运营", source="GEM Tuba", note="来源列示2016年原油产量13.26百万桶；13.26百万÷闰年366日=36.2千桶/日。该数是历史推算年均值，不代表当前产量。"),

    # Iran
    record("伊朗", "Ahvaz", "阿瓦士", "油田", 31.32, 48.68, source="EIA Iran"),
    record("伊朗", "Marun", "马伦", "油田", 31.19, 49.08, source="GEM Marun", note="原列年度数值的原始引文未证实是该年度实际产油总量；撤回据此换算的推算日均。逐田实产待核。"),
    record("伊朗", "Aghajari", "阿加贾里", "油田", 30.70, 49.83, source="GEM Aghajari", note="原列年度数值的原始引文未证实是该年度实际产油总量；撤回据此换算的推算日均。逐田实产待核。"),
    record("伊朗", "Gachsaran", "加奇萨兰", "油田", 30.36, 50.80, source="GEM Gachsaran", note="原列年度数值的原始引文未证实是该年度实际产油总量；撤回据此换算的推算日均。逐田实产待核。"),
    record("伊朗", "Reg-e-Safid", "雷格萨菲德", "油田", 31.03, 49.31, source="EIA Iran"),
    record("伊朗", "South Azadegan", "南阿扎德甘", "油田", 30.06, 48.23, source="GEM South Azadegan", note="原列年度数值的原始引文未证实是该年度实际产油总量；撤回据此换算的推算日均。逐田实产待核。"),
    record("伊朗", "North Azadegan", "北阿扎德甘", "油田", 30.27, 48.25, value="75", metric_type="actual_output", unit="千桶/日", data_date="2019-11-25", source="Trend North Azadegan", note="Trend报道引用伊朗方面消息称日产量75千桶；这是2019年现场产量快照，不代表当前产量。"),
    record("伊朗", "Yadavaran", "雅达瓦兰", "油田", 31.03, 48.16, source="EIA Iran"),
    record("伊朗", "North Yaran", "北亚兰", "油田", 30.81, 48.14, source="EIA Iran"),
    record("伊朗", "South Yaran", "南亚兰", "油田", 30.68, 48.13, source="EIA Iran"),
    record("伊朗", "Azar", "阿扎尔", "油田", 33.08, 46.29, source="EIA Iran"),
    record("伊朗", "Darkhovin", "达尔霍温", "油田", 30.70, 48.48, source="EIA Iran"),
    record("伊朗", "Hendijan", "亨迪詹", "海上油田", 30.24, 49.70, source="EIA Iran"),
    record("伊朗", "Doroud", "多鲁德", "海上油田", 26.06, 53.04, source="EIA Iran"),
    record("伊朗", "Foroozan", "福鲁赞", "海上油田", 26.02, 52.45, source="EIA Iran"),
    record("伊朗", "Soroush", "苏鲁什", "海上油田", 29.70, 50.12, source="EIA Iran"),
    record("伊朗", "Nowruz", "诺鲁兹", "海上油田", 29.35, 50.20, source="EIA Iran"),
    record("伊朗", "Salman", "萨尔曼", "海上油气田", 25.52, 53.39, source="EIA Iran"),

    record("伊朗", "Bibi Hakimeh", "比比哈基梅", "油田", 29.91, 50.46, status="运营", source="GEM Bibi Hakimeh", note="原列年度数值的原始引文未证实是该年度实际产油总量；撤回据此换算的推算日均。逐田实产待核。"),
    record("伊朗", "Karanj", "卡兰吉", "油田", 30.9902, 49.8602, status="运营", source="GEM Karanj", note="原列年度数值的原始引文未证实是该年度实际产油总量；撤回据此换算的推算日均。逐田实产待核。"),
    record("伊朗", "Abuzar", "阿布扎尔", "海上油田", 29.292, 49.532, status="运营", source="GEM Abuzar", note="原列年度数值的原始引文未证实是该年度实际产油总量；撤回据此换算的推算日均。逐田实产待核。"),
    record("伊朗", "Mansouri", "曼苏里", "油田", 30.9289, 48.828, status="运营", source="GEM Mansouri", note="原列年度数值的原始引文未证实是该年度实际产油总量；撤回据此换算的推算日均。逐田实产待核。"),
    record("伊朗", "Sepehr-Jufair", "塞佩赫尔—朱费尔", "油田项目群", 31.298, 48.059, status="运营", source="GEM Sepehr-Jufair", note="原列年度数值的原始引文未证实是该年度实际产油总量；撤回据此换算的推算日均。逐田实产待核。"),
    record("伊朗", "Parsi", "帕西", "油田", 31.0718, 49.9237, metric_type="undisclosed", status="运营", source="GEM Parsi", note="GEM列为运营油田，属于Parsi-Paranj开发项目；项目合计量未分配给单一油田，故单田日产量留空。"),
    record("伊朗", "Bahregansar", "巴赫雷甘萨尔", "海上油田", 29.916667, 49.7, metric_type="undisclosed", status="运营", source="GEM Bahregansar", note="GEM列为运营海上油田但未给坐标；地图点位取NGA地名数据库油田点（29.916667, 49.7）作近似位置。未找到可核验的单田日产量。"),
    record("伊朗", "Sirri E", "锡里E", "海上油气田", 25.751, 54.632, status="运营", source="GEM Sirri E", note="原列年度数值的原始引文未证实是该年度实际产油总量；撤回据此换算的推算日均。逐田实产待核。"),
    record("伊朗", "Masjed Soleyman", "马斯杰德苏莱曼", "油田", 31.9325, 49.3105, status="运营", source="GEM Masjed Soleyman", note="原列年度数值的原始引文未证实是该年度实际产油总量；撤回据此换算的推算日均。逐田实产待核。"),

    # 公开地图中的位置为近似中心点，二手名录仅用于确认名称和位置，不据此填写未经核实的实产。
    record("伊朗", "Pazanan", "帕扎南", "油田", 30.4532, 50.1354, source="GEM Pazanan", note="公开资产名录；逐田持续日产量未核验。"),
    record("伊朗", "Kupal", "库帕尔", "油田", 31.3118, 49.3203, source="GEM Kupal", note="公开资产名录；逐田持续日产量未核验。"),
    record("伊朗", "Dehloran", "德赫洛兰", "油田", 32.5516, 47.1077, source="GEM Dehloran", note="公开资产名录；逐田持续日产量未核验。"),
    record("伊朗", "Paranj", "帕兰吉", "油田", 30.95, 49.85, source="GEM Paranj", note="与Parsi同属开发项目；不拆分项目合计产量。"),
    record("伊朗", "Nargesi", "纳尔格西", "油田", 29.4742, 51.2602, source="GEM Nargesi", note="公开资产名录；逐田持续日产量未核验。"),

    # Kuwait
    record("科威特", "Burgan", "布尔干", "油田", 29.05, 47.91, source="KOC / KPC"),
    record("科威特", "Magwa", "马格瓦", "油田", 29.17, 47.92, source="KOC / KPC"),
    record("科威特", "Ahmadi", "艾哈迈迪", "油田", 28.99, 48.08, source="KOC / KPC"),
    record("科威特", "Raudhatain", "劳达泰因", "油田", 30.20, 47.66, source="KOC / KPC"),
    record("科威特", "Sabriya", "萨布里亚", "油田", 30.28, 47.74, source="KOC / KPC"),
    record("科威特", "Bahra", "巴赫拉", "油田", 29.95, 47.46, source="KOC / KPC"),
    record("科威特", "Ratqa", "拉特卡", "油田", 30.13, 47.59, source="KOC / KPC"),
    record("科威特", "Umm Niqa", "乌姆尼卡", "重油田", 30.10, 47.68, value="22.14", metric_type="actual_output", unit="千桶/日", data_date="FY2023/24（日点未注明）", source="KOC Annual Report 2023-24", note="KOC年报称FY2023/24在Umm Niqa实现22,140桶/日；报告未将其定义为全年平均。"),
    record("科威特", "South Ratqa", "南拉特卡", "重油田", 30.02, 47.70, source="KOC / KPC"),
    record("科威特", "Minagish", "米纳吉什", "油田", 29.00, 46.38, source="KOC / KPC"),
    record("科威特", "Umm Gudair", "乌姆古代尔", "油田", 28.70, 46.52, source="KOC / KPC"),
    record("科威特", "Abdali", "阿卜达利", "油田", 30.03, 47.93, source="KOC / KPC"),
    record("科威特", "Wafra", "瓦夫拉", "跨境油田", 28.72, 47.90, source="KOC / KPC", note="沙特—科威特中立区共享资产。"),
    record("科威特", "Khafji", "哈夫吉", "跨境海上油田", 28.52, 48.42, source="KOC / KPC", note="沙特—科威特中立区共享资产。"),
    record("科威特", "Nokhetha", "诺赫萨", "发现海上油田", None, None, status="2024年发现；商业生产未证实", source="KOC Annual Report 2024-25", note="KOC年报的2,800桶/日是Nokhetha-1勘探井测试流量，不能填作全田持续日产量。"),
    record("科威特", "Julaiah", "朱莱亚", "发现海上油田", None, None, status="2025年发现；商业生产未证实", source="KOC Annual Report 2024-25", note="KOC年报仅披露勘探井测试与资源量，未披露全田持续日产量。"),

    # Qatar
    record("卡塔尔", "Al Shaheen", "阿尔沙欣", "海上油田", 26.51, 51.92, value="280.1", metric_type="actual_output", unit="千桶/日", data_date="2024年平均", source="QatarEnergy", note="QatarEnergy官方投资者演示文稿列示的2024年平均原油产量；来源直报。"),
    record("卡塔尔", "Dukhan", "杜汉", "油气田", 25.42, 50.79, value="176.4", metric_type="actual_output", unit="千桶/日", data_date="2024年平均", source="QatarEnergy", note="QatarEnergy官方投资者演示文稿列示的2024年平均原油产量；来源直报。"),
    record("卡塔尔", "Al-Rayyan", "阿尔拉扬", "海上油田", 25.98, 51.33, value="3.6", metric_type="actual_output", unit="千桶/日", data_date="2024年平均", source="QatarEnergy", note="QatarEnergy官方投资者演示文稿列示的2024年平均原油产量；来源直报。"),
    record("卡塔尔", "Al-Khaleej", "阿尔哈利杰", "海上油田", 25.70, 51.48, value="23.4", metric_type="actual_output", unit="千桶/日", data_date="2024年平均", source="QatarEnergy", note="QatarEnergy官方投资者演示文稿列示的2024年平均原油产量；来源直报。"),
    record("卡塔尔", "Idd El-Sharqi", "伊德谢尔基", "海上油田", 25.59, 51.31, value="54.4", metric_type="actual_output", unit="千桶/日", data_date="2024年平均", source="QatarEnergy", note="QatarEnergy官方投资者演示文稿列示的2024年平均原油产量；来源直报。"),
    record("卡塔尔", "Karkara", "卡尔卡拉", "海上油田", 25.46, 51.33, source="QatarEnergy"),
    record("卡塔尔", "Maydan Mahzam", "迈丹马赫赞", "海上油田", 25.20, 51.20, value="16.2", metric_type="actual_output", unit="千桶/日", data_date="2024年平均", source="QatarEnergy", note="QatarEnergy官方投资者演示文稿列示的2024年平均原油产量；来源直报。"),
    record("卡塔尔", "Bul Hanine", "布尔哈宁", "海上油田", 25.06, 51.14, value="35.1", metric_type="actual_output", unit="千桶/日", data_date="2024年平均", source="QatarEnergy", note="QatarEnergy官方投资者演示文稿列示的2024年平均原油产量；来源直报。"),
    record("卡塔尔", "North Field", "北方气田", "气田", 26.62, 51.45, source="QatarEnergy", note="气田，不与原油日产量比较。"),

    # Oman
    record("阿曼", "Mukhaizna", "穆凯兹奈", "油田", 19.34, 56.47, source="Occidental Oman", note="运营商确认油田运营及累计产量，但未找到可核验的2023年单田8万桶/日实产；撤回该值。"),
    record("阿曼", "Yibal", "伊巴尔", "油田", 22.26, 56.15, source="GEM Yibal", note="原列年度数值的原始引文未证实是该年度实际产油总量；撤回据此换算的推算日均。逐田实产待核。"),
    record("阿曼", "Natih", "纳蒂赫", "油田", 22.48, 56.33, source="PDO"),
    record("阿曼", "Fahud", "法胡德", "油田", 22.35, 56.50, source="PDO"),
    record("阿曼", "Qarn Alam", "卡恩阿拉姆", "油田", 22.55, 57.07, source="PDO"),
    record("阿曼", "Marmul", "马尔穆勒", "油田", 18.12, 55.22, source="PDO"),
    record("阿曼", "Nimr", "尼姆尔", "油田", 18.76, 55.74, source="PDO"),
    record("阿曼", "Lekhwair", "莱赫韦尔", "油田", 20.59, 57.14, source="PDO"),
    record("阿曼", "Bahja", "巴赫贾", "油田", 20.96, 56.80, source="PDO"),
    record("阿曼", "Harweel", "哈维尔", "油田群", 18.08, 55.62, source="PDO"),
    record("阿曼", "Amal", "阿迈勒", "油田", 18.48, 55.72, source="PDO"),

    record("阿曼", "Yumna", "尤姆纳", "海上油田", 19.9841, 58.546, value="742", metric_type="actual_output", unit="桶/日", data_date="2026年3月平均（31天生产期）", status="生产中", source="Masirah Oil Yumna", note="运营方公告称31天生产期内全田总产量日均742桶；Block 50运营方持有100%权益。"),
    record("阿曼", "Bisat", "比萨特", "油田", 21.178, 55.8542, metric_type="undisclosed", status="运营", source="OQ / GEM Bisat", note="OQ于2023年公告比萨特油田原油处理设施投产；GEM列为运营油田，逐田日产量未披露。坐标为公开地图资料的近似点。"),
    record("阿曼", "Daleel", "达利勒", "油田", 22.7241, 55.976, status="运营", source="Daleel Petroleum", note="运营商披露Block 5共有五个主要油田；区块约5万桶/日不能分配给单田。"),
    record("阿曼", "Shadi", "沙迪", "油田", None, None, status="运营", source="Daleel Petroleum", note="Block 5油田；仅有区块合计产量，单田和坐标未核验。"),
    record("阿曼", "Bushra", "布什拉", "油田", None, None, status="运营", source="Daleel Petroleum", note="Block 5油田；仅有区块合计产量，单田和坐标未核验。"),
    record("阿曼", "Mazoon", "马祖恩", "油田", None, None, status="运营", source="Daleel Petroleum", note="Block 5油田；仅有区块合计产量，单田和坐标未核验。"),
    record("阿曼", "Furat", "富拉特", "油田", None, None, status="运营", source="Daleel Petroleum", note="Block 5油田；仅有区块合计产量，单田和坐标未核验。"),
    record("阿曼", "Safah", "萨法", "油田", None, None, status="运营", source="Occidental Oman", note="Occidental披露Block 9的主要油田；未披露可核验单田日产量。"),
    record("阿曼", "Wadi Latham", "瓦迪拉萨姆", "油田", None, None, status="运营", source="Occidental Oman", note="Occidental披露Block 9的主要油田；未披露可核验单田日产量。"),
    record("阿曼", "Khamilah", "哈米拉", "油田", None, None, status="运营", source="Occidental Oman", note="Occidental披露Block 27油田；未披露可核验单田日产量。"),

    # Bahrain and Yemen
    record("巴林", "Bahrain Field (Awali)", "巴林／阿瓦利油田", "油田", 26.07, 50.55, value="39.5", metric_type="actual_output", unit="千桶/日", data_date="2022年平均", source="UNFCCC Bahrain BTR", note="UNFCCC BTR列示2022年原油与凝析油年均产量39.5千桶/日。"),
    record("巴林", "Abu Safah", "阿布萨法", "跨境海上油田", 26.02, 50.61, value="≈300", metric_type="actual_output", unit="千桶/日", data_date="BTR1（基准日未注明）", source="UNFCCC Bahrain BTR", note="报告称全油田产量约300千桶/日，未注明观察日期；巴林权益为50%，约150千桶/日为权益份额而非全田产量。"),
    record("也门", "Masila", "马西拉", "油田／14区块", 14.47, 49.54, source="Yemen Ministry of Oil", note="冲突环境下缺少可靠连续逐田日产量。"),
    record("也门", "East Shabwa", "东舍卜瓦", "油田／10区块", 14.55, 47.54, source="Yemen Ministry of Oil"),
    record("也门", "Hawareem", "哈瓦里姆", "油田／32区块", 14.32, 48.96, source="Yemen Ministry of Oil"),
    record("也门", "Alif", "阿利夫", "油田／18区块", 15.35, 45.05, source="Yemen Ministry of Oil"),
    record("也门", "Jannah", "詹纳", "油田／5区块", 15.24, 45.16, source="Yemen Ministry of Oil"),

    # Syria, Israel and Turkey
    record("叙利亚", "Al-Omar", "奥马尔", "油田", 35.07, 40.60, value="15", metric_type="actual_output", unit="千桶/日", data_date="2026-02-22", source="Le Monde Al-Omar 2026", note="记者实地采访运营主任称日产1.5万桶；2026-01-19较早报道约5千桶/日，修复期波动很大。"),
    record("叙利亚", "Al-Tanak", "塔纳克", "油田", 35.10, 40.34, source="Syria public reporting"),
    record("叙利亚", "Al-Jafra", "贾夫拉", "油田", 35.05, 40.47, source="Syria public reporting"),
    record("叙利亚", "Al-Ward", "瓦尔德", "油田", 35.20, 40.55, source="Syria public reporting"),
    record("叙利亚", "Al-Taym", "泰姆", "油田", 35.23, 40.26, source="Syria public reporting"),
    record("叙利亚", "Rmeilan", "鲁迈兰", "油田", 37.04, 42.03, source="Syria public reporting"),
    record("叙利亚", "Suwaydiya", "苏韦迪耶", "油田", 37.07, 41.93, source="Syria public reporting"),
    record("以色列", "Heletz", "赫莱兹", "油田", 31.57, 34.62, source="Israel Ministry of Energy", note="当前实际产量和停产状态未获可靠公开确认。"),
    record("以色列", "Meged", "梅格德", "油田", 32.28, 35.03, source="Israel Ministry of Energy"),
    record("以色列", "Leviathan", "利维坦", "气田", 32.58, 34.78, source="Israel Ministry of Energy", note="气田。"),
    record("以色列", "Tamar", "塔马尔", "气田", 31.99, 34.33, source="Israel Ministry of Energy", note="气田。"),
    record("以色列", "Karish", "卡里什", "气田", 32.62, 33.94, source="Israel Ministry of Energy", note="气田。"),
    record("以色列", "Tanin", "塔宁", "气田", 32.73, 34.10, source="Israel Ministry of Energy", note="气田。"),
    record("土耳其", "Raman", "拉曼", "油田", 37.86, 41.16, source="TPAO"),
    record("土耳其", "Batı Raman", "西拉曼", "油田", 37.88, 41.05, source="TPAO"),
    record("土耳其", "Garzan", "加尔赞", "油田", 37.75, 41.45, source="TPAO"),
    record("土耳其", "Şelmo", "谢尔莫", "油田", 37.77, 41.69, source="TPAO"),
    record("土耳其", "Gabar", "加巴尔", "油田群", 37.40, 42.45, source="TPAO"),
]
